### ISSUE TITLE
RTSP疑问

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#10]
func (s *UDPServer) RunLoop() error {
		for {
			b := make([]byte, udpMaxPacketLength)
			l, a, e := s.conn.ReadFromUDP(b)
			if e != nil && (l < 0 || l > udpMaxPacketLength) {
				nazalog.Errorf("ReadFromUDP length invalid. length=%d", l)
			}
			s.onReadUDPPacket(b[:l], a.String(), e)
		}
	}
	func (p *PubSession) onReadUDPPacket函数中固定偏移判断数据内容。
	每次固定读取1500字节，如果发端每次发送数据小于MTU大小，比如每个包700如果出现包粘连，是否能正确处理？
	如果发端就是小于1500字节RTP包，如果IP层丢失部分IP分片是否会导致后面数据全部错乱？

**Comment by q191201771** [comment]
1. 不会，这种情况下，一个包要么没收到，要么完整收到，不会出现收一半丢一半的情况，不会出现多个包粘连的情况。
2. 不会，发送端业务层已经按MTU切割了数据，那么丢失一个IP分片，其实也就是丢失了一个业务层的RTP包。

我猜你可能还想知道，假如一个业务层的包大于MTU，拆分多个IP后，丢失了其中一个IP分片会怎样？
据我个人理解，这种情况，接收端的内核就不会把这个包返回给业务层了。

这也就是为什么要在发送端的业务层把包按MTU进行切割的根本原因。
因为不切割，丢一个分片，整个包就丢了，丢包损失太大。
当然也不能切割得太小，因为切割得越小，包的数量就越多。

接收端需要有能处理RTP包丢失的能力。
所以，每个RTP都有固定的包头。
比如lal中
https://github.com/q191201771/lal/blob/master/pkg/rtsp/rtp_composer.go
简单演示了如何组装多个rtp包为一个业务层的视频帧或音频帧数据。
以及rtp包丢失时，该如何合帧，该如何放弃无法合成的帧。
不过，目前lal中，暂时没有加入丢包重传的算法。以后做WebRTC就会加了。

**Comment by bigbao9494** [comment]
明白，发出这个ISSU后我查了一下UDP没有粘包的，IP分片那个就是你说的那样。之前是我没有弄明白…………
