### ISSUE TITLE
h.264, h.265 测试视频，rtsp无法支持

### ISSUE THREAD

**Issue by joyhope** [q191201771/lal#100]
这个2个测试视频

https://test-videos.co.uk/bigbuckbunny/mp4-h264  
https://test-videos.co.uk/bigbuckbunny/mp4-h265

h.264 用rtmp推送正常，用rtsp 推送接收报告异常。 h.265 rtsp 通用报告异常。

**Comment by q191201771** [comment]
感谢反馈。
列表里不止一个文件，具体用的哪个？
用rtsp推送是用ffmpeg吗？具体命令是啥？
能否提供一下日志，感谢。

**Comment by joyhope** [comment]
记录的命令是

ffmpeg -re -stream_loop -1 -i Big_Buck_Bunny_1080_10s_30MB-h.264.mp4 -c copy -f rtsp rtsp://localhost:5544/live/test110
ffmpeg -re -stream_loop -1 -i Big_Buck_Bunny_1080_10s_30MB-h.265.mp4 -c copy -f rtsp rtsp://localhost:5544/live/test110

这些都会failure. 

H.264 lal 出现持续出现。

2021/07/20 09:51:04.201646  WARN [HLSMUXER1] OnFrame V not opened. boundary=false, key=false - muxer.go:179
2021/07/20 09:51:04.201701  WARN [HLSMUXER1] OnFrame V not opened. boundary=false, key=false - muxer.go:179
2021/07/20 09:51:04.201739  WARN [HLSMUXER1] OnFrame V not opened. boundary=false, key=false - muxer.go:179
2021/07/20 09:51:04.401535  WARN [HLSMUXER1] OnFrame V not opened. boundary=false, key=false - muxer.go:179

H.265 不出现问题，但是vlc 无法打开视频。

**Comment by q191201771** [comment]
这个视频有B帧，目前lalserver的rtsp不支持B帧。
你有试过其他开源服务吗？是否有支持的？

**Comment by joyhope** [comment]
rtsp-simple-server 在linux环境上，能支持h.264, h.265 在rtsp上都没问题。（windows上好像有问题），rtmp h.265有问题（这个正常的，标准不支持）。 我测试毕竟粗略，主要是看一下各自的特点。

lal 非常不错。

**Comment by q191201771** [comment]
“rtsp-simple-server 在linux环境上，能支持h.264, h.265 在rtsp上都没问题。”

是指rtsp推流，rtsp拉流吗？推流用的也是上面的ffmpeg命令以及视频文件吗？拉流用的什么软件？

感谢提供信息，如果它支持lalserver不支持，我后续会做相应的开发。

**Comment by joyhope** [comment]
>是指rtsp推流，rtsp拉流吗？推流用的也是上面的ffmpeg命令以及视频文件吗？拉流用的什么软件？

使用方式和在lal上使用，ffmpeg 以文件形式 rtsp形式 publish， 用vlc 的rtsp pull .

**Comment by q191201771** [comment]
超时关闭了，有问题请随时重新打开或创建新的issue。
