### ISSUE TITLE
使用rtmp推流到ZLMediaKit，数据中有AMF0Type=NULL的会失败

### ISSUE THREAD

**Issue by BenLocal** [q191201771/lal#102]
ZLMediaKit中rtmp body中有AMF0Type=NULL的数据，导致出现unknown type. vt=5的错误
![image](https://user-images.githubusercontent.com/18746523/126862581-3470664a-9898-445c-9009-e0204140c416.png)

pkg\rtmp\amf0.go line306中是否可以添加：
```
case Amf0TypeMarkerNull:
	index += 1
```

**Comment by q191201771** [comment]
好的，感谢反馈，我会修复这个问题，
请问是推流还是拉流，影响功能吗，

**Comment by BenLocal** [comment]
推流的，读取服务端返回的amf0 object数据的时候

**Comment by q191201771** [comment]
看到你提交的pr了，提两点建议：

1. 读取null类型数据时，使用ReadNull方法，而不是直接index+1，避免后续index越界。具体写法可以参照ReadObject中对其他类型读取的代码。
2. ReadArray中也可以增加读取null类型的处理，增强兼容性

另外补充一点，根据我抓包分析，报错并不是由于onBWDone这个消息引起的，这个消息中Null数据并不是object类型内的子数据，真正引起报错的是rtmp connect信令所对应的结果返回的信令，也即`_result('NetConnection.Connect.Success')`

**Comment by BenLocal** [comment]
是我想当然了，debug确实是NetConnection.Connect.Success的导致的错误，下次会注意，抱歉
还有就是请教一下，用wireshark抓包，为什么我没有找到_result('NetConnection.Connect.Success')这个包
![image](https://user-images.githubusercontent.com/18746523/126978823-3de80075-2446-4c63-9f3c-398b3dbbb70b.png)

**Comment by q191201771** [comment]
代码我已经合并进master分支了，
感谢贡献PR，希望以后多多参与，
wireshark解析的问题我也不太清楚额，
