### ISSUE TITLE
rtmp 配置 gop_num不起作用

### ISSUE THREAD

**Issue by dzh592204** [q191201771/lal#105]
我在windows下修改rtmp 配置项gop_num ; 把这个值设置为0或者5，通过vlc拉流播放，二者延迟一样。都是1-2s左右

**Comment by q191201771** [comment]
首先，GOP缓存生效的前提是，推流发生在拉流之前，你是先推流再拉流吗？
你可以通过在日志中搜索`gop num`来获取是否发送GOP缓存给播放者。

另外，GOP缓存主要是提高流打开时间，是否增加延迟和播放器的实现有关，播放器可以选择快放追赶，从而在一段时间后达到和没有GOP缓存一样的延时。
