### ISSUE TITLE
How to use http_notify (on_pub_start ) in PHP ?

### ISSUE THREAD

**Issue by IPTVUNION** [q191201771/lal#107]
**hello 
Thanks for this script
I have problem getting PHP information. No posts from scripts**
example:
`  "http_notify": {
    "enable": true,
    "update_interval_sec": 5,
    "on_pub_start": "http://127.0.0.1:982/on_pub_start.php" 
  },`

rtmp : rtmp://127.0.0.1:1925/live/test?token=1111
 **Streaming is done, but it is not POST TO  on_pub_start.php**
php address : http://127.0.0.1:982/on_pub_start.php

**Nothing is received $_REQUEST $_POST  OR  $_REQUEST['stream_name'] $_POST['stream_name']
AND 
  file_put_contents('request.txt',json_encode($_REQUEST) );**

**How to use this ?**

**Comment by IPTVUNION** [comment]
> **hello Thanks for this script I have problem getting PHP information. No posts from scripts**
> example:
> ` "http_notify": { "enable": true, "update_interval_sec": 5, "on_pub_start": "http://127.0.0.1:982/on_pub_start.php" },`
> 
> rtmp : rtmp://127.0.0.1:1925/live/test?token=1111
> **Streaming is done, but it is not POST TO on_pub_start.php**
> php address : http://127.0.0.1:982/on_pub_start.php
> 
> **Nothing is received $_REQUEST $_POST OR $_REQUEST['stream_name'] $_POST['stream_name'] AND file_put_contents('request.txt',json_encode($_REQUEST) );**
> 
> **How to use this ?**

I understood the solution.


     **$data = json_decode(file_get_contents('php://input'), true);
        $data["url_param"]**
   

A question of how to stop RTMP from API ?

**Comment by q191201771** [comment]
You can using HTTP API `api/ctrl/kick_out_session ` to stop RTMP.
There is a document for HTTP API, but saddly not English version, check this out:

https://pengrl.com/lal/#/HTTPAPI
