### ISSUE TITLE
转发流，从腾讯云接流，然后写代码将流重新转推给腾讯云，但是有些流可以播放有些流不可以播放，有碰到过这种情况吗

### ISSUE THREAD

**Issue by coderyw** [q191201771/lal#109]

**Comment by coderyw** [comment]
是基于你那个rtmp2pushrtmp示例改写的。基本上都是你那个代码逻辑。但是日志里面显示的是，没有报错，stats统计也正常，然后推流到腾讯云就是播不了，后面我重启一下服务，又可以播了，很奇怪的问题，
![1635764145340_55E10393-2FC2-42DF-91C3-B41991B39189](https://user-images.githubusercontent.com/45194379/139661683-b3d537de-bb78-40ae-a4a9-8e759855d274.png)

**Comment by q191201771** [comment]
播放不了时你尝试以下操作：
1. 播放转推前的源流，看是否正常
2. 用`lal/app/demo/pullrtmp`拉取播放不了的转推流（以及源流），看看是否能生成正常的flv文件

**Comment by coderyw** [comment]
源流是正常的，有个很奇怪的现象，就是我一开始正常推流，然后手动在腾讯云后台把流给断了。我这边做了重连机制，重连后继续推流，日志输出也很正常，但是，腾讯云就播不了。帧率一直波动很大，不知道为啥。但是源流正常的。

**Comment by q191201771** [comment]
你用的啥播放器，试试别的播放器呢，
或者使用lalserver作为服务器接收转推流试试，

**Comment by coderyw** [comment]
使用的是vlc播放的，不行。

**Comment by q191201771** [comment]
超时关闭了，有问题请重新打开或创建新的issue，感谢。
