### ISSUE TITLE
推流端网线断开或直接掉电，服务端无法快速检测到

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#11]
func (c *ChunkComposer) RunLoop(reader io.Reader, cb OnCompleteMessage)
	对io.ReadAtLeast的调用需要正常TCP超时才能结束,时间比较久
	超时后err := session.RunLoop()返回，回到func (server *Server) handleTCPConnect
	再执行server.obs.OnDelRTMPPubSession(session)

**Comment by q191201771** [comment]
你测试的是多久，目前设置的阈值是10秒。
见 rtmp/server_session.go 中的 serverSessionReadAVTimeoutMS

**Comment by bigbao9494** [comment]
不只10秒应该有好几十秒吧。

**Comment by q191201771** [comment]
现在lalserver中的上层逻辑logic.Group中每间隔10秒会检查所有的会话，如果会话不活跃了会主动断开连接。
欢迎测试并反馈。
