### ISSUE TITLE
HLS如何pull

### ISSUE THREAD

**Issue by iyear** [q191201771/lal#113]
一个直播的 `https://xxx.com/xxx.m3u8` 如何进行hls的Pull操作

翻看了一下源码和demo，似乎还没实现？只找到rtmp转hls然后进行Sub的demo

**Comment by q191201771** [comment]
是的，目前没有hls的pull，只有sub。
请问你的场景是怎样的，pull后需要存储为m3u8+ts文件，还是有其他需求呢。

**Comment by iyear** [comment]
> 是的，目前没有hls的pull，只有sub。 请问你的场景是怎样的，pull后需要存储为m3u8+ts文件，还是有其他需求呢。

是想pull然后remux成flv再sub

**Comment by q191201771** [comment]
好的，已加入需求池，暂时没有排期时间。
