### ISSUE TITLE
rtmp断连续推播放器不断开

### ISSUE THREAD

**Issue by lzw5399** [q191201771/lal#121]
一旦上游拉流或者接收推流因为某些原因断开(网络抖动等), 是否能增加一个配置能把流重新拉起来

比如增加一个超时时间的配置，在超时时间内能重新把流拉起来，保持播放器不断

**Comment by q191201771** [comment]
当前相关的策略：

1. pub推流和sub拉流没有时序要求，允许先sub拉流再pub推流
2. pub推流有超时时间，10秒没有收到数据会主动关闭pub连接
3. sub拉流同第2条
4. pull回源时，会判断是否有sub拉流，如果没有sub拉流了，pull会主动断开
5. pull回源断开，会重新pull（当然，前提是满足4）

这块接下来会补充一些文档，提供一些配置项，并补充更多的策略特性。
欢迎提建议，感谢。
