### ISSUE TITLE
Live Rtmp push

### ISSUE THREAD

**Issue by onthegit** [q191201771/lal#122]
Hello,

thanks for the project. I was looking at the demos and could not find how to push live rtmp to another rtmp server. I saw pull rtmp to rtmp, 
Does this library support pushing live rtmp sessions to another rtmp url?
Also the same question applies for saving the live session to FLV file? is it possible?

Thanks.

**Comment by q191201771** [comment]
hi,

`lal/app/demo/pullrtmp2pushrtmp` can pull live rtmp stream from whatever rtmp server to another rtmp url.
`lal/app/demo/pullrtmp` can pull live rtmp stream from whatever rtmp server and save to flv file.

And if you are talking about that the live rtmp stream is already in lalserver, lalserver also supports `relay_push` and `record` by itself, you can start with `lal/conf/lalserver.conf.json` and search `relay_push` and `record`.

**Comment by onthegit** [comment]
Hello, @q191201771  thanks for your reply. I was talking about live RTMP session (that is already being processed by lalserver) for pushing to another RTMP url.
OBS studio streams to => lalserver=>lalserver pushes that stream to another RTMP url.

**Comment by q191201771** [comment]
If another RTMP address is constant static, you can use `relay_push` with the config file.
If dynamic, use HTTP notify and HTTP API.

**Comment by joy2fun** [comment]
> Hello, @q191201771 thanks for your reply. I was talking about live RTMP session (that is already being processed by lalserver) for pushing to another RTMP url. OBS studio streams to => lalserver=>lalserver pushes that stream to another RTMP url.

 Hi @onthegit, did you come up with any solution to relay the stream to a different url ?
