### ISSUE TITLE
开启 hls 并启用 use_memory_as_disk_flag 后，cleanup_mode 为0或者1时，会出现内存持续增长

### ISSUE THREAD

**Issue by universix** [q191201771/lal#126]
开启 hls 并启用 use_memory_as_disk_flag 后，m3u8 和 ts 会存储在内存中
当 cleanup_mode 为1或者2时，不会持续删除过期的 ts 文件，导致内存持续增长
建议在手册的 lalserver 配置文件说明 中注明

**Comment by q191201771** [comment]
Hi，

cleanup_mode为1或者2时，
开启use_memory_as_disk_flag也会清理，清理内存的时机和写磁盘模式一样。

请提供更多的信息给我：
1. 实测时的场景，包含流数量，时长，相关的具体配置，内存增长了多少，如果能给我一个pprof的采用文件就更好了
2. 使用的Go版本

感谢。

**Comment by universix** [comment]
抱歉，可能我没有描述清楚，而且标题描述有错误
这个不是指内存泄漏，至少在我测试中没有发现内存泄漏。
设想一个直播场景，一个长期的视频流通过拉或者推输入到 lal，如果 cleanup_mode 为0（不删除m3u8+ts文件，可用于录制等场景）和1（在输入流结束后删除m3u8+ts文件），此时启用 use_memory_as_disk_flag，lal 的内存会逐渐增长，因为流一直在输入，ts 文件一直在产生并保存在内存中，所以建议在手册中注明一下。
将 hls 保存在内存其实是一个非常非常棒的功能，在需要的场景中使用，可以避免低效的硬盘io，由内存直接进行网络io

**Comment by q191201771** [comment]
好的，我之后在文档注明一下。

**Comment by q191201771** [comment]
在配置文件文档中添加了提醒。

https://pengrl.com/lal/#/ConfigBrief
