### ISSUE TITLE
建议 hls 加入 append_list 功能

### ISSUE THREAD

**Issue by universix** [q191201771/lal#127]
A 当结束 lal 后再启动后：
1. 如果输入的流不再重新输入，之前生成的 m3u8 和 ts 会一直存在
2. 如果输入的流重新输入，会从 0 重新生成新的 ts 和 m3u8，再启动 lal 前的 ts 在流持续期间会持续存在，即使 cleanup_mode 为 2 也不会被清理

B 当输入的流中断，然后重新输入时，会从 0 重新生成新的 ts 和 m3u8，中断前的 ts 在流持续期间会持续存在，即使 cleanup_mode 为 2 也不会被清理

以上 A、B 两种情况下，即使 cleanup_mode 为 2，都会导致内存或者硬盘空间出现“泄漏”，特别是输入流的中断频繁时，累计的过期没有清理的 ts 会占用大量空间，这些 ts 没有被 m3u8 索引，也不会被访问。

建议增加类似 ffmpeg 的 hls_flags 中的 append_list 功能，即使流中断或者 lal 重启，也可以在 m3u8 中持续索引 ts，即可以更好的管理 ts，又可以比较好的维护一个包含多个 ts 的 m3u8，避免一次中断就要重新索引。

**Comment by q191201771** [comment]
超时加入 #37 中管理。
