### ISSUE TITLE
建议增加 HTTP-ts 的 pull

### ISSUE THREAD

**Issue by universix** [q191201771/lal#128]
看到 #113 的需求已经在 In process，建议同时增加 HTTP-ts 的 pull
其实使用场景比较接近，在需要 hls pull 的场景，也有一些是 HTTP-ts 的流

**Comment by q191201771** [comment]
好的，同样是加入需求池，没有排期时间。

**Comment by q191201771** [comment]
加入 #37 管理了，后续进度有变化会在两边同时更新。
