### ISSUE TITLE
HLS VOD support?

### ISSUE THREAD

**Issue by KudryavtsevDmitry** [q191201771/lal#131]
Hello. I have several questions about features
1. Does it support HLS VOD? If so, does it make it on-the-fly packaging (without writing/storing chunks on disk)
2. Does it support mp4, mp3 containers?

**Comment by q191201771** [comment]
1
yes, it supports HLS VOD (and Live mode both).
yes, it supports (with or) without writing/storing chunks on disk.

2
no, not support mp3, mp4 yet.

**Comment by KudryavtsevDmitry** [comment]
Do you have demo or example of config file for HLS VOD  setup?

**Comment by q191201771** [comment]
example of using the default config:

push stream:

ffmpeg -re -stream_loop -1 -i /Volumes/extssd/avfile/wontcry.flv -acodec copy -vcodec copy -f flv rtmp://127.0.0.1/live/test110

play HLS VOD:

ffplay http://127.0.0.1:8080/hls/test110/record.m3u8
