### ISSUE TITLE
hls流第一次 playlist.m3u8 record.m3u8 一定会有 #EXT-X-DISCONTINUITY

### ISSUE THREAD

**Issue by CundhiAdams** [q191201771/lal#133]
最新的代码下，cleanup_mode 设置为0后，record.m3u8 内容如下

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:0

#EXT-X-DISCONTINUITY
#EXTINF:3.000,
test110-1646980864881-0.ts
#EXTINF:3.000,
test110-1646980867926-1.ts
#EXTINF:3.000,
test110-1646980870917-2.ts
#EXTINF:3.000,
test110-1646980873919-3.ts
#EXTINF:0.566,
test110-1646980876918-4.ts
#EXT-X-ENDLIST

**Comment by q191201771** [comment]
好的，会尽快处理。
感谢反馈。

**Comment by q191201771** [comment]
超时移入 #37 管理。
