### ISSUE TITLE
直播截图和视频录制、回放

### ISSUE THREAD

**Issue by zkbqhuang** [q191201771/lal#14]
请问大神，这个项目会集成实现：直播截图和视频录制、回放等这些功能吗？

**Comment by zkbqhuang** [comment]
还是说这些都应该在 客户端实现？ 然后在业务服务器处理存储和流播放相关，
或者用minio（https://github.com/minio/minio）作为储存方案，另起一个独立服务单独处理间隔时段进行截图、录制，存储。

**Comment by q191201771** [comment]
会集成录制功能，包含flv和m3u8格式，mp4也可能会支持，
回放可能会集成，
截图不会集成，因为涉及到解码，可以自己使用ffmpeg做，

**Comment by zkbqhuang** [comment]
喔，了解，或许截图应该放在客户端做，然后上传服务器缓存或存储。

**Comment by q191201771** [comment]
master分支已支持HLS录制回放，后续还会增加flv格式录制。

测试方法：
推流地址： `rtmp://127.0.0.1:19350/live/test110`
HLS直播地址： `http://127.0.0.1:8081/hls/test110/playlist.m3u8`
HLS录制回放地址： `http://127.0.0.1:8081/hls/test110/record.m3u8`

具体见：《[常见推拉流客户端软件的使用方式](https://pengrl.com/p/20051/)》

**Comment by q191201771** [comment]
录制目前已支持： hls, flv, ts
后续可能会支持： mp4

配置文件说明参见： https://pengrl.com/lal/#/ConfigBrief

**Comment by q191201771** [comment]
清理一些过期的issues，
这个issue还剩mp4录制没有实现，暂时没有排期，先归档到 #37，这个issue先关闭了，
有问题随时沟通，感谢，
