### ISSUE TITLE
rtmp推流大小分辨率超过平时常规大小宽度 HLS切片不能正常工作？

### ISSUE THREAD

**Issue by sboy2000** [q191201771/lal#143]
因为需要测试一些拼接后的视频推流，视频分辨率大小非常规大小，推流后 切片HLS和其它的都工作不正常
    Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)
    displayWidth    : 4096
    displayHeight   : 2048
    fps             : 0
    profile         :
    level           :
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(progressive), 4096x2048 [SAR 1:1 DAR 2
:1], q=2-31, 1999 kb/s, 7.50 fps, 15 tbr, 1k tbn, 1k tbc

推流4096 X 2048大小后 hls切片 flv等 都不能正常工作，自动切片识别为1920*1088的视频大小，图像也无内容了 其它的flv也是

**Comment by sboy2000** [comment]
目前4K的普及后 这个分辨率支持应该扩大 可以放到8k分辨率的支持吧？

**Comment by q191201771** [comment]
感谢反馈。
请问是使用什么推流的，推流协议是什么，我应该如何复现这个问题。

**Comment by sboy2000** [comment]
使用的FFMPEG推流的  推流协议RTMP   但我保存本地一个TS视频文件同样大的 推又不会产生这样问题。难道不是分辨率引起的 是metadata元信息？ffmpeg显示正确的4096 X 2048的 nginx rtmp也好 lal也好 接收显示的 都是1920 1088 自动切片不正常。但是nodemedia 显示不正常 但是hls切片的结果是正常的

**Comment by sboy2000** [comment]
复现的问题和视频源 我发你Q邮箱吧 因为视频源地址不能随便对外发 需要测试复现可以单独给你PM 下

**Comment by joestarzxh** [comment]
测试 3840x2160 的视频mp4 FFmpeg推rtmp流，没有发现此问题

**Comment by sboy2000** [comment]
@joestarzxh 哥们可以给个联系方式 我单独发能复现的视频源 因为内容不能随便乱发出去的 可能也是这个源的问题 我也是单独用视频文件又不复现，唯独这个合成拼接的这个视频会复现

**Comment by joestarzxh** [comment]
邮箱79490763@qq.com,最好给q191201771大大。我不一定能解决

**Comment by q191201771** [comment]
我试了一下，rtmp、flv、rtsp是正常的，hls和mpegts不正常，应该是转换mpegts的问题。

你从nginx rtmp module拉取hls正常吗？

我有空会继续跟这个问题。

备注信息：
流的分辨率比较大
流是纯视频的，没有音频

**Comment by q191201771** [comment]
hi，这个问题我已经修复了，你拉最新代码测试一下。
原因是rtmp seq header中的sps pps不太标准，需要兼容性处理一下，使用后面nalu中的sps pps。

**Comment by sboy2000** [comment]
感谢大大的修复。目前测试OK，能正常工作。我们这里还有很多非常规流的，我会继续测试下！综合下来大大的作品相当的不错，我会继续跟进大大的作品
