### ISSUE TITLE
期望老板提供一些对外接口

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#15]
接口清单 ：

1. cpu利用率
2.内存利用率
3.网络实时状态：进+出实时带宽 ，以字节为单位
4.连接情况： flv,rtmp,hls,及其他格式的识别

5.流列表信息：

	ID，	Appname，Streamname,IP：port，Audio(Codec，freq,channel) Video(codec,size,fps), StartTime(上线时间）,PreStartTime(上次上线时间),Clients(正在读流的客户端个数），Op(禁止流,启用流)

6.系统信息
	OS版本
	体系框架（计算机的）
	内存配置
	cpu配置
	系统开机时间、服务开启时间

config文件：
	用户名，密码

**Comment by q191201771** [comment]
好的，老板，已记录在小本本上，后续会开发。
第一期只会提供和服务自身相关信息的接口，不会提供机器、环境相关的信息。
请期待后续版本。

**Comment by zsinba** [comment]
谢谢老板

**Comment by zsinba** [comment]
老板， 不提供系统级接口。可以提供这样一个接口：
当前有多少流在系统上；
每个流的上线时间，音频和视频的编码格式；
这个流有多少观众；
以上是统一接口；还有一个单个查询的接口，传入流的appname/streamname后，查询这个流的信息，如果有则返回流信息，如果没有则返回掉线时间。

参考HTTP状态码，正常返回200，非正常返回其他状态码。

**Comment by q191201771** [comment]
master分支已实现部分HTTP API接口，欢迎使用，并继续提意见，
HTTP API接口对应文档：https://pengrl.com/p/20100/
