### ISSUE TITLE
demo/pullhttpflv/pullhttpflv 保存的flv是分散文件，

### ISSUE THREAD

**Issue by talway** [q191201771/lal#151]
能否保存未一个文件或转为mp4文件

这个demo希望保留，

demo：analyseflv  这个没有保存功能

**Comment by q191201771** [comment]
用 httpflv.PullSession 拉流，然后用 httpflv.FlvFileWriter 保存为文件就可以了。

**Comment by talway** [comment]
> httpflv.FlvFileWriter 保
用 httpflv.PullSession 拉流
https://github.com/q191201771/lal/blob/master/app/demo/pullhttpflv/pullhttpflv.go

这个是有的，看到了

但是 httpflv.FlvFileWriter  在哪里的，没找到的
