### ISSUE TITLE
期望老板提供将rtmp保存为hls的demo

### ISSUE THREAD

**Issue by xubigshu** [q191201771/lal#16]
拉取一路rtmp流，然后将其保存为hls格式
辛苦大佬啦

**Comment by q191201771** [comment]
好的，老板，已记录在小本本上。

**Comment by q191201771** [comment]
demo已提供，地址为：
https://github.com/q191201771/lal/blob/master/app/demo/pullrtmp2hls/pullrtmp2hls.go

**Comment by xubigshu** [comment]
感谢老板！
