### ISSUE TITLE
Unble push stream to Wowza RTMP Server with authencation

### ISSUE THREAD

**Issue by hungnt1** [q191201771/lal#167]
Hi all,
I am trying push rtmp to wowza with user and password but i cann't work.
without password, it still works normally

My command format: pullrtsp2pushrtmp.go  -i rtsp://root:@xxx.196:8555/live1s2.sdp   -o rtmp://xxx:1935/hung/mystream -t 0

![image](https://user-images.githubusercontent.com/29896020/167527353-831d6133-2a54-4d46-af01-85948f8195d2.png)

Plz help me
Tks u

**Comment by q191201771** [comment]
Ok, we are digging; and will relay you ASAP.

**Comment by ZSC714725** [comment]
rtmp推流 adobe模式鉴权交互流程如下：
例如：推流url为rtmp://zang:123456@100.100.108.220:1935/livetest/test110，其中用户名为zang，密码为123456

（1）第一次TCP连接
server回复_error信令，Property 'code' String 'NetConnection.Connect.Rejected'和Property 'description' String '[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ] : '

（2）第二次TCP连接
client发送connect中的Property 'app' String 'livetest/test110?authmod=adobe&user=zang'和Property 'tcUrl' String 'rtmp://100.100.108.220:1935/livetest/test110?authmod=adobe&user=zang'
server回复_error信令，Property 'code' String 'NetConnection.Connect.Rejected'和Property 'description' String '[ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=zang&salt=PJuw1w==&challenge=6fruuQ==&opaque=6fruuQ=='

（3）第三次TCP连接
client发送connect中Property 'app' String 'livetest/test110?authmod=adobe&user=zang&challenge=xNJABQ==&response=POsdGoxLEjAupogeAEVxHg==&opaque=6fruuQ=='和Property 'tcUrl' String 'rtmp://100.100.108.220:1935/livetest/test110?authmod=adobe&user=zang&challenge=xNJABQ==&response=POsdGoxLEjAupogeAEVxHg==&opaque=6fruuQ=='

其中第三次response的算法如下：
（1）salt1 = base64(md5(username|salt|password)，其中salt为第二次交互server回复中的值
（2）response = base64(md5(salt1|opaque|challenge2)，其中opaque为第二次交互server回复的值，challenge2为client端随机生成，也可以使用server回复的challenge，client第三次交互时发送的challenge需为challenge2

**Comment by q191201771** [comment]
Pushing RTMP to Wowza has been done.
Try it.

@hungnt1

**Comment by ZSC714725** [comment]
> Thank you so much team. I have tried and succeeded when push to wowza. But there is some issue in application name. it make duplicate application name and stream name like bellow. My publish url like: rtmp://hung:123@xxx:1935/hung/live, but show in wowza
> 
> ![image](https://user-images.githubusercontent.com/29896020/168506575-84f919f1-991e-4a76-90a8-f23b2ca694fb.png)


If the stream name is not added in the application name, the wowza will always reply to 403, resulting in no further authentication.

**Comment by hungnt1** [comment]
> > Thank you so much team. I have tried and succeeded when push to wowza. But there is some issue in application name. it make duplicate application name and stream name like bellow. My publish url like: rtmp://hung:123@xxx:1935/hung/live, but show in wowza
> > ![image](https://user-images.githubusercontent.com/29896020/168506575-84f919f1-991e-4a76-90a8-f23b2ca694fb.png)
> 
> If the stream name is not added in the application name, the wowza will always reply to 403, resulting in no further authentication.

Tks u . I understand

**Comment by q191201771** [comment]
Hi, @hungnt1 
Do you still have a problem with this issue or have already been satisfied with the current solution?

**Comment by hungnt1** [comment]
> Hi, @hungnt1 Do you still have a problem with this issue or have already been satisfied with the current solution?

It's working fine now

**Comment by ZSC714725** [comment]
https://blog.csdn.net/qq_25543483/article/details/124761445?spm=1001.2014.3001.5502

**Comment by hungnt1** [comment]
> https://blog.csdn.net/qq_25543483/article/details/124761445?spm=1001.2014.3001.5502

helpful. Tks u
