### ISSUE TITLE
支持音频编码格式PCMU

### ISSUE THREAD

**Issue by q191201771** [q191201771/lal#168]
1. 整理PCMU在各封装协议中的支持情况，包含rtmp，flv，rtsp，hls，webrtc，ts，mp4（如有遗漏，请补充）
2. lal全面支持PCMU的计划

全面支持的意思是：

1. 支持PCMU的协议，对应的pub，sub，push，pull协议栈需要支持
2. lalserver中，转封装时，不同协议间，支持的要转，不支持的，要过滤，不要引起错误甚至崩溃

计划的意思是，将整个任务拆分，方便阶段性提交。

比如粒度小一点的子任务，可以是rtmp pull协议栈支持。
粒度大一点的，可以是支持PCMU通过rtmp pub进入到lalserver系统，该转转，该过滤过滤，所有功能都通过测试。

**Comment by ZSC714725** [comment]
1、在rtsp转rtmp的过程中，测试发现存在一个问题，PCMU和PCMA当采样率为非8000时，ffplay或者VLC播放声音不正常
分析过程如下

- FLV的Audio Tag中采样率只有0-5500，1-11000，2-22000，3-44000，且PCMU和PCMA在填充Tag时Header只有1个字节，没有单独的字段去表明具体的分辨率
- ffplay和VLC播放显示的分辨率都是8000Hz，非预期
- 使用ZLMediaKit测试也有同样的问题
<img width="861" alt="image" src="https://user-images.githubusercontent.com/22109318/218313604-ebf78882-3663-40ac-8132-a884fd0c080e.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/22109318/218313674-d413f520-8efe-48a9-b381-3356053e673b.png">

**Comment by q191201771** [comment]
已支持。
