### ISSUE TITLE
Standalone RTMP server

### ISSUE THREAD

**Issue by ivanjaros** [q191201771/lal#17]
Hi,
I am looking for a solid RTMP server library. So far I have used https://github.com/nareix/joy4 but that one is unsupported for quite some time and so I am looking for some up-to-date highly optimized alternative. And I found your project and https://github.com/gwuhaolin/livego and so I wonder how does your RTMP implementation compare with livego's and if there is a chance you can refactor RTMP part of this project into standalone library? I read some issues with livego's performance so I wonder how your verison compares.

**Comment by q191201771** [comment]
Do you wanna a RTMP server library to build your own app, or just a RTMP server?

Currently,
app/lalserver can work as a RTMP server, and you can disable other protocol and some feature by config file, and that would be a standlone RTMP server.

For RTMP library:
- `pkg/rtmp` provide the pure RTMP part. e.g. a Server struct to running a RTMP server, it handle RTMP connection as ServerSession struct. You can read av data from PubSession, and write av data to SubSession.
- `pkg/logic` provide the logic part. e.g. link RTMP PubSession to RTMP SubSession by stream name, and broadcast the av data.

Welcome to tell me more about what you need, and that will help me improve lal.

For the performance part, you can bench and compare with other RTMP server by yourself.
by the way, lal provide two client demo can use as bench tools:

`app/demo/pushrtmp`

```
# create n PushSession(as rtmp client which push stream to rtmp server)
# usage:
$./bin/pushrtmp -i testdata/test.flv -o rtmp://127.0.0.1:19350/live/test_{i} -r -n 1000
```

`app/demo/pullrtmp`

```
# create n PullSession(as rtmp client which pull stream from rtmp server)
# usage:
# 1. pull the same stream by n PullSession
$./bin/pullrtmp -i rtmp://127.0.0.1:19350/live/test -n 1000
# 2. pull different stream by n PullSession
$./bin/pullrtmp -i rtmp://127.0.0.1:19350/live/test_{i} -n 1000
```

Give me the feedback of bench result, I will keep improving performance.

**Comment by ivanjaros** [comment]
i just need a server where i can set a handler that will give me the h264/aac packets which i can then process on my own. like http server where you set up your own handlers but in this case just the main handler. so library.

**Comment by q191201771** [comment]
Yeah, the library you needed is exactly what package rtmp(in lal/pkg/rtmp) does.

You set a handler to rtmp.Server, run it, when new client connected, you got a callback named OnNewRTMPPubSession.
then you set a hander to rtmp.ServerSession, when server recved h264/aac packets, you got a callback named OnReadRTMPAVMsg.

That's it. pretty simple.

Check these out:

- pkg/rtmp/server.go
- pkg/rtmp/server_session.go

**Comment by ivanjaros** [comment]
sounds like what i need. thanks.
