### ISSUE TITLE
使用ffplay拉流播放，很久才能正常播放，提示missing picture in access

### ISSUE THREAD

**Issue by kyle-hy** [q191201771/lal#174]
ffplay http://172.16.10.140:8080/live/test110.flv
ffplay version 5.0.1 Copyright (c) 2003-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[h264 @ 0x7fc1b771c3c0] missing picture in access unit with size 9  
[h264 @ 0x7fc1b771c3c0] missing picture in access unit with size 9  
[h264 @ 0x7fc1b771c3c0] missing picture in access unit with size 9  
[h264 @ 0x7fc1b771c3c0] missing picture in access unit with size 9  
[h264 @ 0x7fc1b771c3c0] missing picture in access unit with size 9  
Input #0, flv, from 'http://172.16.10.140:8080/live/test110.flv':   
  Metadata:
    version         : lal0.29.1
  Duration: N/A, start: 19225.732000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2560x1440, 1k tbr, 1k tbn
[swscaler @ 0x7fc1b81f2000] [swscaler @ 0x7fc1bb213000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fc1b81f2000] [swscaler @ 0x7fc1be40e000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fc1b81f2000] [swscaler @ 0x7fc1be422000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fc1b81f2000] [swscaler @ 0x7fc1be436000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fc1b81f2000] [swscaler @ 0x7fc1be44a000] deprecated pixel format used, make sure you did set range correctly
[h264 @ 0x7fc1b8059fc0] no frame!   0KB vq=  611KB sq=    0B f=0/0   
[h264 @ 0x7fc1b8063e80] no frame!   0KB vq=  621KB sq=    0B f=0/0   
[h264 @ 0x7fc1b806dd40] no frame!   0KB vq=  620KB sq=    0B f=0/0   
[h264 @ 0x7fc1b8077c00] no frame!   0KB vq=  612KB sq=    0B f=0/0   
[NULL @ 0x7fc1b771c3c0] missing picture in access unit with size 9   
    Last message repeated 1 times
[NULL @ 0x7fc1b771c3c0] missing picture in access unit with size 9   
    Last message repeated 2 times
[h264 @ 0x7fc1b8081b00] no frame!   0KB vq= 4806KB sq=    0B f=0/0

**Comment by kyle-hy** [comment]
启用gop_num配置项后解决拉流播放慢的问题。start_relay_pull请求后首次播放依然慢。

**Comment by q191201771** [comment]
hi，请问还有问题吗，问题自己解决了吗？

我补充几点哈：

1
ffmpeg的missing picture的那个错，含义是h264中有视频帧解码不了，常见于SEI帧，这个不影响视频流解码

2
ffplay时，可以在末尾加上 -analyzeduration 10000000，加快打开时间
该参数的含义：
`specify how many microseconds are analyzed to probe the input`

3
你的流是只有视频没有音频吗，如果是的话，可以尝试使用lalserver的叠加静音音频功能(将配置文件中的add_dummy_audio_enable设置为true)，可以解决某些播放器播放纯视频的流的打开慢的问题
