### ISSUE TITLE
streaming ffmpeg to lal on demand ?

### ISSUE THREAD

**Issue by goliveok** [q191201771/lal#178]
hi 
Is it possible to add this option?

It is a permanent connection with ffmpeg. It starts  on demand streaming when the first client connects and stops when the last client exits. not stop ffmpeg to rtmp lal ?

This option to reduce consumption download when multi urls stream.

  Thank you for this excellent program. 
    You always surprise us with something new.

**Comment by q191201771** [comment]
What protocol is FFmpeg pulling?

**Comment by goliveok** [comment]
example:

ffmpeg to lal rtmp:
ffmpeg -i stream-url -c copy -f flv rtmp://localhosst:1935/live/test1

after lal send to all clients.
It starts on demand streaming from ffmpeg when the first client connects and stops when the last client exits. not stop ffmpeg to rtmp lal ?

**Comment by q191201771** [comment]
Currently, you can get the first client connects event and the last client exits event by HTTP-Notify(on_sub_start, on_sub_stop).
And you can start or stop FFmpeg when these HTTP-Notify triggers.

Also, lalserver will add HTTP-API to support start and stop FFmpeg.

**Comment by q191201771** [comment]
超时移入 #37 管理。
