### ISSUE TITLE
期望老板 rtsp的支持

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#18]
rtsp进入lal; 
从lal拉rtsp的流出来 ; 

以及rtsp的流进来,rtmp的流出来(包括flv,hls); 
and  从lal拉rtsp/rtmp/flv/hls; 无论 是从哪个协议过来的; 

期望的结果是rtsp得到很好的支持. 

谢谢老板 .

**Comment by q191201771** [comment]
目前已支持：rtsp -> rtsp/rtmp/http-flv/hls/http-ts
后续可能会增加其他协议转成rtsp流出来。
欢迎测试，感谢。

**Comment by zsinba** [comment]
感谢老板.

**Comment by zsinba** [comment]
顶
