### ISSUE TITLE
rtmp 配置 gop_num的具体作用

### ISSUE THREAD

**Issue by echo-LuGuang** [q191201771/lal#183]
```
"gop_num": 0,                        //. RTMP拉流的GOP缓存数量，加速流打开时间，但是可能增加延时
                                         //. 如果为0，则不使用缓存发送
```
文档中说明可以加快流打开速度。
请问有推荐的值吗？比如8h8g服务器推荐的值是 8 - 16。

**Comment by q191201771** [comment]
和配置关系不是特别大，和播放器有关系。
一般开启的话，设置成1~3差不多了。
具体你要自己测试，看流打开时间（从开始拉流到播放出来的时间），以及延迟时间（推流这边说你好，播放那边听到你好的时间间隔），取个自己满意的值。
