### ISSUE TITLE
期望老板能提供一个flv的播放器

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#19]
现在播放flv使用flvjs的各种魔改的版本,都存在共同的问题; 
比如 断流播放; 追帧算法; ios下面的播放等; 

期望老板能考虑下,使用wasm的方式提供 播放器，来解决从lal出来的流的播放的需求 ；

这方面主要应用在：
1. web上面 ；
2. 微信上面；
3. H5的app上面；

**Comment by q191201771** [comment]
没有接触过web播放器开发，将该issue移入 #37 中管理了，后续有空可能会学习这方面的知识。
