### ISSUE TITLE
HTTP API命令添加指定房间

### ISSUE THREAD

**Issue by echo-LuGuang** [q191201771/lal#191]
### 一、HTTP API命令添加指定房间
1、开始录制 `可以指定目录、文件名、视频格式、每个视频文件的时长，超出时长会生成另外一个文件继续录制`
2、停止录制 `notify再加一个视频文件录制完毕的通知，api也能主动查询`

_Originally posted by @echo-LuGuang in https://github.com/q191201771/lal/issues/164#issuecomment-1148313570_

**Comment by q191201771** [comment]
超时移入 #37 管理。
