### ISSUE TITLE
lal_record\hls\test文件夹下的视频文件一直在增长

### ISSUE THREAD

**Issue by wangdemon** [q191201771/lal#192]
lal_record\hls\test文件夹下的视频文件一直在增长，在推流的过程中，能控制该文件夹的的视频数量吗？
![1](https://user-images.githubusercontent.com/20681339/172798585-0788f2fa-d6b2-405d-8fec-cd97f8abe0ad.png)
![2](https://user-images.githubusercontent.com/20681339/172798599-cf623589-5a86-4c16-9d92-2291d3d0db56.png)

**Comment by q191201771** [comment]
参考配置文件文档中 hls -> cleanup_mode 的内容
[lalserver 配置文件说明](https://pengrl.com/lal/#/ConfigBrief?id=lalserver-%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6%e8%af%b4%e6%98%8e)

**Comment by wangdemon** [comment]
好的，谢谢您
