### ISSUE TITLE
需要加个web管理后台，

### ISSUE THREAD

**Issue by talway** [q191201771/lal#194]
需要加个web管理后台，

**Comment by kuuyee** [comment]
这个我准备搞一下 :)

**Comment by q191201771** [comment]
感谢对lal的喜爱与支持。
第三方开发者如果有兴趣开发基于lalserver的web管理后台：

可以使用lal的HTTP-API和HTTP-Notify接口，通过http以松耦合的方法和lalserver交互。

可以创建自己的工程，自己的开源项目。
后续如果想贡献给我，可以提交给我，我会评估是否合并到lal或lalext项目中。

**Comment by talway** [comment]
免费的基于 Lal 直播流媒体服务管理系统，支持支持国标GB28181（待实现），Onvif协议。包含视频墙管理和摄像头管理功能，登陆账号admin/admin。https://github.com/btagrass/lsm
