### ISSUE TITLE
如何在rtmp 的PushSession中发送metadata数据包？

### ISSUE THREAD

**Issue by chekun** [q191201771/lal#196]
如题

**Comment by q191201771** [comment]
PushSession只有一个发送函数，也即Write函数，签名是这样的：
func (s *PushSession) Write(msg []byte) error
可用于发送序列化好的二进制数据


如果你有metadata的key、value数据，
不知道怎么序列化成amf格式的metadata，
请参考 rtmp.BuildMetadata 函数，
签名是这样的：
func BuildMetadata(width int, height int, audiocodecid int, videocodecid int) ([]byte, error)
这个函数只写了固定的几个key，有需要添加其他key的话，你可以参照着自己实现一个类似的函数。


如果你已经有amf格式的metadata数据，比如通过上面的BuildMetadata生成的，或者通过lal的库得到的base.RtmpMsg类型的数据，或者自己生成好了，
不知道怎么序列化成rtmp chunk格式的数据，
请参考 rtmp.Message2Chunks 函数，
签名是这样的：
func Message2Chunks(message []byte, header *base.RtmpHeader) []byte


更详细的内容，请参考以上这几个函数的实现，以及在lal中是如何使用的。

**Comment by chekun** [comment]
感谢老大

amf0.WriteObject 缺失float64写入，我加了一个

#197
