### ISSUE TITLE
Push RTMP not working with YouTube

### ISSUE THREAD

**Issue by abrar71** [q191201771/lal#199]
`app/demo/pushrtmp/pushrtmp.go` is not working with YouTube Live Stream and closes connection after the set deadline. I've tried using many different flv videos but doesn't work with YouTube though Facebook live works smoothly.

Error with YouTube:
```shell
push failed. err=context deadline exceeded - pushrtmp.go:100
```

**Comment by q191201771** [comment]
We will check this issue.

**Comment by q191201771** [comment]
Fixed, try again.

**Comment by abrar71** [comment]
Thank you! It's fixed now.
