### ISSUE TITLE
期望老板提供webrtc的支持

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#20]
这包括三个方面的webrtc支持；
1. 使用webrtc推流到lal
2. 从lal出来webrtc的视频流，使用video进行播放；
3. 从其他webrtc的流拉回来播放；

这里面会使用stun/turn的协议，建议老板直接使用第三方的，有go的，也有c/C++的。 不建议老板自己实现这块。

**Comment by puzzle9** [comment]
则一个个老板叫的

**Comment by 63isOK** [comment]
真不建议将webrtc集成进来,直播和互动两条线都可以走的很长.webrtc的体量非常大,真的要做,也建议新开一个仓库做一个webrtc的适配即可.ps:pion非常走心.

建议将lal深入打磨,不要做成类似srs的大杂烩.

**Comment by q191201771** [comment]
@63isOK 

lalserver这个app应该不会集成webrtc的功能。
等lal的功能都做完了，我会做webrtc方面的工作。到时候应该会做其他的app。

和webrtc交互涉及到音频转码，
lalserver当前的定位是尽量不依赖第三方库，尤其是不直接或间接依赖非Go的库。

欢迎提出更多建议，感谢。
