### ISSUE TITLE
pub接入自定义流 数据帧部分与接入相机流不一致

### ISSUE THREAD

**Issue by fallowu** [q191201771/lal#205]
首先感谢大佬的项目👍👍👍
### 需求
基于lal库做自己的应用，通过自定义流，接入lalserver服务，以rtsp的形式提供给第三方使用。
### 版本
v0.30.1
### 实现
自定义二次开发参考 [customize_lalserver.go ](https://github.com/q191201771/lal/blob/master/app/demo/customize_lalserver/customize_lalserver.go)已实现。
### 差异
自定义流与接入相机流后，第三方应用从lalserver拉取rtsp的时候，数据帧中的sps和pps有区别。

- 直接接入相机流(RTSP H264)，sdp回调有sps和pps，数据帧也有完整sps和pps。

- 自定义接入流时，sdp回调中有sps和pps，数据帧中没有sps和pps。

### 影响
会给第三方应用（比如录像）带来额外的工作量

![image](https://user-images.githubusercontent.com/3997050/180736040-f47ce5b8-5b1c-4f75-821e-a6455b46c5d8.png)

### 解决方式
自己做了个简单处理，在判断是关键帧时，关键处追加了sps和pps信息。
```
spps := append(r.sps[:], append(avc.NaluStartCode4, r.pps...)...)
nal = append(spps, append(avc.NaluStartCode4, nal...)...)
r.clearVideoSeqHeader()
```

https://github.com/q191201771/lal/blob/82f092128f584aedb7bf2b2e02acdbc9e0416b68/pkg/remux/avpacket2rtmp.go#L197

**Comment by q191201771** [comment]
issue写的非常详细，感谢提供case。
提个PR吧，免得自己暗改lal内部的代码，以后不好维护。

添加一个全局配置，到pkg/remux/var.go中，比如：

var AvPacket2RtmpRemuxerAddSpsPps2KeyFrameFlag = false

AvPacket2RtmpRemuxer通过该配置走新老逻辑：false为老逻辑，true为新逻辑。

该配置默认值为false，业务方可以在自己的main函数中设置。

---

lal中的一些原有逻辑，临时记录如下：

一. ICustomizePubSessionContext, CustomizePubSessionContext, IAvPacketStream

使用AvPacket2RtmpRemuxer，注意，没有使用InitWithAvConfig传递sps、pps
也即sps、pps必须通过数据接口传入

二. AvPacket2RtmpRemuxer

输出的seq header来源有两个：
1) InitWithAvConfig接口直接设置
2) packet中包含sps、pps

注意，如果packet中包含sps、pps，那么转换为rtmp video message时，会去除sps、pps

三. Rtmp2RtspRemuxer

输出的sdp完全来自输入的seq header

输入的rtmp video message如果包含sps、pps，那么切割rtp中也会包含。
相应的，rtmp中不包含，rtp中也不包含。

**Comment by fallowu** [comment]
看了下现有方法，InitWithAvConfig 接口直接设置，感觉内部也走FeedAvPacket方法比较好。
但是有一个问题，针对	AvPacketPtAac     AvPacketPt = 97 音频，如果没有通过InitWithAvConfig 设置，是否可以播放？


对比了 InitWithAvConfig 和 FeedVideo两个方法：
InitWithAvConfig 里使用的是	RtmpAacPacketTypeSeqHeader       = 0
FeedVideo里使用的是	RtmpAacPacketTypeRaw             = 1
```
func MakeAudioDataSeqHeaderWithAsc(asc []byte) (out []byte, err error) {
	if len(asc) < minAscLength {
		return nil, nazaerrors.Wrap(base.ErrShortBuffer)
	}

	// 注意，前两个字节是SequenceHeaderContext，后面跟着asc
	out = make([]byte, 2+len(asc))
	out[0] = 0xaf
	out[1] = 0
	copy(out[2:], asc)
	return
}
```
```
length := len(pkt.Payload) + 2
payload := make([]byte, length)
// TODO(chef) 处理此处的魔数0xAF
payload[0] = 0xAF
payload[1] = base.RtmpAacPacketTypeRaw
copy(payload[2:], pkt.Payload)
r.emitRtmpAvMsg(true, payload, pkt.Timestamp)
```

**Comment by fallowu** [comment]
> issue写的非常详细，感谢提供case。 提个PR吧，免得自己暗改lal内部的代码，以后不好维护。
> 
> 添加一个全局配置，到pkg/remux/var.go中，比如：
> 
> var AvPacket2RtmpRemuxerAddSpsPps2KeyFrameFlag = false
> 
> AvPacket2RtmpRemuxer通过该配置走新老逻辑：false为老逻辑，true为新逻辑。
> 
> 该配置默认值为false，业务方可以在自己的main函数中设置。
> 
> lal中的一些原有逻辑，临时记录如下：
> 
> 一. ICustomizePubSessionContext, CustomizePubSessionContext, IAvPacketStream
> 
> 使用AvPacket2RtmpRemuxer，注意，没有使用InitWithAvConfig传递sps、pps 也即sps、pps必须通过数据接口传入
> 
> 二. AvPacket2RtmpRemuxer
> 
> 输出的seq header来源有两个：
> 
> 1. InitWithAvConfig接口直接设置
> 2. packet中包含sps、pps
> 
> 注意，如果packet中包含sps、pps，那么转换为rtmp video message时，会去除sps、pps
> 
> 三. Rtmp2RtspRemuxer
> 
> 输出的sdp完全来自输入的seq header
> 
> 输入的rtmp video message如果包含sps、pps，那么切割rtp中也会包含。 相应的，rtmp中不包含，rtp中也不包含。


看了下现有方法，InitWithAvConfig 接口直接设置，感觉内部也走FeedAvPacket方法比较好。
但是有一个问题，针对	AvPacketPtAac     AvPacketPt = 97 音频，如果没有通过InitWithAvConfig 设置，是否可以播放？


对比了 InitWithAvConfig 和 FeedVideo两个方法：
InitWithAvConfig 里使用的是	RtmpAacPacketTypeSeqHeader       = 0
FeedVideo里使用的是	RtmpAacPacketTypeRaw             = 1
```
func MakeAudioDataSeqHeaderWithAsc(asc []byte) (out []byte, err error) {
	if len(asc) < minAscLength {
		return nil, nazaerrors.Wrap(base.ErrShortBuffer)
	}

	// 注意，前两个字节是SequenceHeaderContext，后面跟着asc
	out = make([]byte, 2+len(asc))
	out[0] = 0xaf
	out[1] = 0
	copy(out[2:], asc)
	return
}
```
```
length := len(pkt.Payload) + 2
payload := make([]byte, length)
// TODO(chef) 处理此处的魔数0xAF
payload[0] = 0xAF
payload[1] = base.RtmpAacPacketTypeRaw
copy(payload[2:], pkt.Payload)
r.emitRtmpAvMsg(true, payload, pkt.Timestamp)
```

**Comment by q191201771** [comment]
我上面的回复分两部分内容，中间有一个分割线分隔。
第一部分是针对PR的建议，你看这部分就可以了。
第二部分没什么用，你可以忽略。

**Comment by q191201771** [comment]
我想了一下，
这个操作应该放在Rtmp2RtspRemuxer更合适，
放在AvPacket2RtmpRemuxer会导致rtmp协议不标准，
请按如下设置帮我测试，感谢，

remux.AvPacket2RtmpRemuxerAddSpsPps2KeyFrameFlag = false
remux.RtspRemuxerAddSpsPps2KeyFrameFlag = true

**Comment by fallowu** [comment]
> 我想了一下， 这个操作应该放在Rtmp2RtspRemuxer更合适， 放在AvPacket2RtmpRemuxer会导致rtmp协议不标准， 请按如下设置帮我测试，感谢，
> 
> remux.AvPacket2RtmpRemuxerAddSpsPps2KeyFrameFlag = false remux.RtspRemuxerAddSpsPps2KeyFrameFlag = true
有几个细节
1.开头不需要以分隔开始
2.第二个需要重新计算下长度。
3.第三个flv播放会花屏卡帧[这个我不知道咋回事]
![image](https://user-images.githubusercontent.com/3997050/181148940-4ab4c6bc-1d24-4203-8698-ea1bca55e70f.png)
![image](https://user-images.githubusercontent.com/3997050/181149286-44f8aceb-a49b-4e00-8931-8aa87ed02417.png)

**Comment by q191201771** [comment]
有空的时候再试试，我已经修复了。

**Comment by fallowu** [comment]
已确认OK.

**Comment by q191201771** [comment]
ok，这个issue我关了，有问题可以重新打开或者创建新的issue，感谢。
