### ISSUE TITLE
Deprecation of package ioutil in Go 1.16

### ISSUE THREAD

**Issue by abrar71** [q191201771/lal#207]
the `ioutil` functions need to be changed to `io` packages

`
"io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
`

**Comment by q191201771** [comment]
Yeah, nice idea.
But if we switch to new functionality, we must update our min dependence of Go from 1.14 to 1.16.
I'm gonna add this issue to the TODO list and do this later.

Any more suggestions, or comparisons?

**Comment by abrar71** [comment]
You are right, this issue should be added to TODO list for now. Thank you!

**Comment by q191201771** [comment]
Move to #37

**Comment by q191201771** [comment]
Done by #264 
We've upgraded to Go 1.16 since we needed to use the Go embed feature by https://github.com/q191201771/lal/commit/feb6ed992f9545024a7fdca8b81658951c776aef
