### ISSUE TITLE
想做流量统计，能否在on_sub_stop加上wrote_bytes_sum

### ISSUE THREAD

**Issue by robin-hzc** [q191201771/lal#209]
想达到的效果大致是这样的数据结构。
{
    "server_id": "1",
    "session_id": "FLVSUB1",
    "protocol": "FLV",
    "base_type": "SUB",
    "remotet_addr": "127.0.0.1:51889",
    "url": "http://127.0.0.1:8080/live/test110.flv?token=1111",
    "app_name": "live",
    "stream_name": "test110",
    "url_param": "token=1111",
    "has_in_session": false,
    "has_out_session": true,
    "wrote_bytes_sum":999999,
}

**Comment by q191201771** [comment]
和 #210 重复了，关闭这个，到 #210 讨论。
