### ISSUE TITLE
期望增加HTTPS证书的支持

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#21]
目前只能使用HTTP连接过去播放FLV；
这有 个致命的问题，在HTTPS的页面上面，是不允许 加载HTTP协议的，这造成无法使用；

其他老板可以增加自定义证书的功能，自己上传HTTPS证书，支持HTTPS播放FLV；

目前折衷的解决办法是： 使用nginx反向代理 HTTP协议，然后输出HTTPS协议的流，这样一来，增加了代理的时间，同时加大延时，而且使用复杂度增加；Nginx上面有这块很好的功能，但是并不是所有人都使用Linux，使用Windows的时候，并不能很好的解决这个问题。

**Comment by q191201771** [comment]
好的，老板，已经安排上了。

**Comment by q191201771** [comment]
master分支最新代码已支持HTTPS拉取flv的流。
你试试看。

**Comment by zsinba** [comment]
谢谢老板，已支持。
