### ISSUE TITLE
想做流量统计，能否在on_sub_stop回调接口的数据结构上加上wrote_bytes_sum

### ISSUE THREAD

**Issue by robin-hzc** [q191201771/lal#210]
如果基于on_update的来统计流量可能会有难度,一方面单个节点连接session可能会很多,造成难以处理,
另一方面,回调的时间间隔可能会漏掉一些用户的流量。
想达到的效果大致是这样的。
{
    "server_id": "1",
    "session_id": "FLVSUB1",
    "protocol": "FLV",
    "base_type": "SUB",
    "remotet_addr": "127.0.0.1:51889",
    "url": "http://127.0.0.1:8080/live/test110.flv?token=1111",
    "app_name": "live",
    "stream_name": "test110",
    "url_param": "token=1111",
    "has_in_session": false,
    "has_out_session": true
}

**Comment by q191201771** [comment]
需求是统计整个服务的、从启动至今的累计流量吗？
统计的目的是啥？

可以在`on_pub_stop`和`on_sub_stop`两个接口都增加`read_bytes_sum`和`wrote_bytes_sum`这两个字段。

**Comment by robin-hzc** [comment]
是呀，是想统计单个用户的流量和拉流端所有消耗的流量。 😋

**Comment by q191201771** [comment]
相关PR #211
