### ISSUE TITLE
结束拉流

### ISSUE THREAD

**Issue by DDGRCF** [q191201771/lal#212]
您好，就是如果我有两拉流，一个是rtsp(rtsp://127.0.0.1:5544/live/test)拉流，一个是flv-http(http://192.168.199.120:8080/live/test.flv)拉流，他们名字相同，都是test。如果我只想结束其中一个的拉流该怎么解决呢

**Comment by q191201771** [comment]
你用的是lalserver吗？
两个拉流指的是都从lalserver拉流吗？如果是的话，你停止一个，另外一个不影响。

**Comment by DDGRCF** [comment]
> 你用的是lalserver吗？ 两个拉流指的是都从lalserver拉流吗？如果是的话，你停止一个，另外一个不影响。

是的，然后是通过[/api/ctrl/kick_session](https://pengrl.com/lal/#/HTTPAPI?id=_23-apictrlkick_session)结束拉流吗，但是我要如何获取某个拉流的{
  "stream_name": "test110", // 必填项，流名称
  "session_id": "FLVSUB1"   // 必填项，会话唯一标识
}中的session_id呢

**Comment by q191201771** [comment]
可以通过HTTP-API中的 `/api/stat/group` 等接口获取，或者HTTP-Notify中的一些回调获取。

https://pengrl.com/lal/#/HTTPAPI
https://pengrl.com/lal/#/HTTPNotify

**Comment by DDGRCF** [comment]
> 可以通过HTTP-API中的 `/api/stat/group` 等接口获取，或者HTTP-Notify中的一些回调获取。
> 
> https://pengrl.com/lal/#/HTTPAPI https://pengrl.com/lal/#/HTTPNotify

您好！就是

我停止推流rtmp后，一直重复拉流关闭拉流关闭。。。
![截图 2022-08-26 22-08-42](https://user-images.githubusercontent.com/63622528/186922833-a6f8fc30-d862-483d-92b7-508ec1232186.png)

**Comment by DDGRCF** [comment]
然后，我想的是停止推流后，不能够从该端口再拉流

**Comment by q191201771** [comment]
> "然后，我想的是停止推流后，不能够从该端口再拉流"

你停止推流后，该端口就拉不到这个流了。
但是多个http-flv流的端口是共用的。端口不会关闭。

> "我停止推流rtmp后，一直重复拉流关闭拉流关闭。。。"

这是因为有客户端一直再拉流。这个符合你预期吗，客户端是你控制吗？

**Comment by DDGRCF** [comment]
> > "然后，我想的是停止推流后，不能够从该端口再拉流"
> 
> 你停止推流后，该端口就拉不到这个流了。 但是多个http-flv流的端口是共用的。端口不会关闭。
> 
> > "我停止推流rtmp后，一直重复拉流关闭拉流关闭。。。"
> 
> 这是因为有客户端一直再拉流。这个符合你预期吗，客户端是你控制吗？

客服端是自己控制的，但客服端停止的标志，是能否拉流。。。

**Comment by q191201771** [comment]
超时关闭，移入 #37 管理。
后续可能增加功能，拉取不存在的流回复404并关闭连接。这个功能通过配置选择是否开启。
