### ISSUE TITLE
通过rtsp拉流和http-flv拉流的视频结果不一样

### ISSUE THREAD

**Issue by TengTengCai** [q191201771/lal#217]
![image](https://user-images.githubusercontent.com/20788729/187371094-71608a4a-f8f4-4115-bfc2-70499f5126ea.png)
http-flv拉流图像不全花屏。

**Comment by TengTengCai** [comment]
rtsp是正常的，http协议的都花屏，是需要调整什么参数吗？

**Comment by q191201771** [comment]
请问输入流是什么格式，是如何输入的，

**Comment by TengTengCai** [comment]
通过start_relay_pull接口添加的rtsp输入，编码格式是h.264。
![image](https://user-images.githubusercontent.com/20788729/188350649-6e11f148-558c-4e05-9814-b04547cb8154.png)

**Comment by q191201771** [comment]
问题解决了吗，
可以按下面这个文档抓一份数据给我，我帮你看看，
https://pengrl.com/#/debug_dump

**Comment by q191201771** [comment]
超时关闭。
