### ISSUE TITLE
期望老板考虑对CDN的支持和验证

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#22]
我验证过使用阿里云的CDN， 播放FLV的时候，似乎并没有效果。 
比如： 
https://www.abc.com/abc.flv这个地址是原地址；
使用ali cdn处理好， 访问 https://www.abc.com/abc.flv 会到阿里云的CDN上面。 
但是操蛋的事情是： 
https://www.abc.com/abc.flv 这个地址从CDN有多少路访问，CDN的服务器，就有多少路到源站服务器。造成CDN虽然用了，但是并没有产生效果。没起到CDN的效果；
效率过alicdn的客服，得到的答复是：  flv文件的过期时间太短， 所以一有请求，就直接回源了。 
后来我尝试把flv的播放时延增加到30秒， 倒是起了一点效果。 这时请求的cdn流量不会全部转发到源站了。

但是新的问题出来了 : 
flvplayer做了追帧算法，如果有缓存，会通过倍速的方式吃掉缓存，这又造成了虽然缓存了30秒，但是这30秒马上被追帧算法给吃掉了。

所以老板你要考虑CDN的话，还要考虑播放器。 这是一个大头的现实情况 。

**Comment by q191201771** [comment]
一. CDN合并回源
这个应该CDN厂商处理，详细参考CDN厂商的文档或者向他们咨询。

二. 播放器
这个我目前没有能力做。

感谢。
