### ISSUE TITLE
国标协议：华为摄像头265编码拉取flv黑屏

### ISSUE THREAD

**Issue by ghost** [q191201771/lal#221]
华为摄像头PS流，web端拉取flv。编码264时可以播放，编码265黑屏。

[logs.zip](https://github.com/q191201771/lal/files/9483695/logs.zip)

**Comment by q191201771** [comment]
使用的是最新的代码吗，

**Comment by spring-lab** [comment]
是的

**Comment by q191201771** [comment]
超时关闭。
如果依然存在问题：

1. 请使用最新版本重新测试
2. 如果还有问题，使用 https://pengrl.com/#/debug_dump 描述的方法抓取数据，重新开issue提交给我
