### ISSUE TITLE
期望老板增加推拉流的密钥功能

### ISSUE THREAD

**Issue by zsinba** [q191201771/lal#23]
目前直接推拉，都没有验证，也没有密钥。这知道地址的人，都可以推或者拉。
期望老板增加密钥的功能；

密钥的功能有这样几个坑： 
1. 如果密钥是配置在服务器端，所有的人使用同样的加密算法，会导致一旦泄露，整个服务器涉及的都需要修改这个密码。 那影响范围相当大。 
2. 如果密钥是配置在客户端，则同样出现上面的问题。 客户端通过url来配置访问密钥，这很容易被不同的用户猜到。

研究了sas以及其他的密钥处理，期望老板考虑这样做密钥：

1. 服务端可以配置多个密钥。 这样每个密钥可以用在不同的场合；这个并不难实现，解密的时候根据密钥头或者请求参数，appname等方式来判断使用哪个密钥；
2. 客户端的播放地址，通过不同的密钥进行播放解密。 

这样就可以解决密钥的安全性问题。

上面描述太操蛋了，估计老板理解有问题。

看老板的产品设计吧。

**Comment by q191201771** [comment]
目前通过HTTP Notify + HTTP API的形式，业务方可在自身业务服务中针对流地址参数选择任何合适自己的算法做鉴权。
这个issue先关闭了，有问题请随时回复，感谢。

**Comment by q191201771** [comment]
鉴权功能已经开发完成了，文档见： https://pengrl.com/lal/#/auth
