### ISSUE TITLE
在lal中将rtp packet重组为rtsp帧完成解密后，如何将帧数据继续推流出去？

### ISSUE THREAD

**Issue by Thebigwind** [q191201771/lal#232]
在lal中将rtp packet重组为rtsp帧完成解密后，如何将帧数据继续推流出去？

**Comment by q191201771** [comment]
你是使用lalserver吗，如果是的话，参考Group.OnAvPacket这个函数，它是用于向lalserver中喂入rtsp的帧数据的。
https://github.com/q191201771/lal/blob/master/pkg/logic/group__core_streaming.go#L72

**Comment by Thebigwind** [comment]
> 你是使用lalserver吗，如果是的话，参考Group.OnAvPacket这个函数，它是用于向lalserver中喂入rtsp的帧数据的。 https://github.com/q191201771/lal/blob/master/pkg/logic/group__core_streaming.go#L72

好的，谢谢
