### ISSUE TITLE
After API post server not store changes

### ISSUE THREAD

**Issue by huycxview** [q191201771/lal#239]
Describe how to replicate the issue:
- enable API in config
- start the server
- change something with API or add new start_relay_pull 
- restart the server
result: config file not changed, old config loaded
@q191201771

**Comment by q191201771** [comment]
> change something with API or add new start_relay_pull

What's the specific meaning of changing something, change what?

When restarted, added start_relay_pull will be lost.
Yes, it is.
If you wanna keep the relay pull, you should manage the task by yourself and recall start_relay_pull.

**Comment by huycxview** [comment]
how to auto start relay pull
@q191201771

**Comment by q191201771** [comment]
You check and watch all the tasks by HTTP-API or HTTP-Notify, and decide when to close, also you can restart it when it ended since the server restarted.

You may treat the lal server as a tool and do the management by yourself as you want.

**Comment by huycxview** [comment]
why error
ERROR http notify post error. err=Post "http://127.0.0.1:10101/on_update": dial tcp 127.0.0.1:10101: connect: connection refused, url=http://127.0.0.1:10101/on_update, info={EventCommonInfo:{ServerId:1} Groups:[]} - http_notify.go:178

**Comment by q191201771** [comment]
HTTP-Notify means that lal server calls your service by HTTP so that the event and information can pass to you.
You should create your HTTP server and serve to receive it.

**Comment by huycxview** [comment]
is it possible to increase pull_timeout_ms to higher than default 5000
@q191201771

**Comment by q191201771** [comment]
Yes, it's a param of API you can config it.

https://pengrl.com/lal/#/HTTPAPI?id=_21-apictrlstart_relay_pull

Check this out, though it's written in Chinese.

**Comment by q191201771** [comment]
Feel free to open a new issue if needed.
