### ISSUE TITLE
Integrating RTMFP into the features

### ISSUE THREAD

**Issue by al-sabr** [q191201771/lal#24]
Hi!

I would like to pin point this missing protocol concerning p2p RTMP.
Would it be possible to integrate the existing code from this repo?

https://github.com/Yuhang/xserver/tree/master/pkg/xserver/rtmfp

Best Regards

**Comment by q191201771** [comment]
Glad to know that someone using rtmfp.
I'm not familiar with rtmfp yet.
You could try integrate by yourself.
and once I have time, I may learn and implement it.

thanks.

**Comment by al-sabr** [comment]
Hi thank you for your answer, I would love to implement it myself but I don't have much experience concerning network programming with Go.

But if you would like to get to know more about it I gathered a knowledge base for another project that will implement it. I hope this helps.

**Comment by ROBERT-MCDOWELL** [comment]
ti would be great to implement RTMFP, it will open door to a lot of great features Flash had for 10 years now.
