### ISSUE TITLE
希望加个读取h264流推到rtmp服务的demo

### ISSUE THREAD

**Issue by hbally** [q191201771/lal#240]
老板 ^_^，添加个demo  h264push2rtmp

**Comment by q191201771** [comment]
超时移入 #37 管理。
现阶段可以参考这两个demo：

(1). customize_lalserver，演示了读取h264文件，通过定制化将内存数据传入到lalserver中
https://github.com/q191201771/lal/blob/master/app/demo/customize_lalserver/customize_lalserver.go#L92

(2). pushrtmp，演示了读取flv文件，使用rtmp协议通过网络传输到lalserver中
