### ISSUE TITLE
关于文档中命名PushSession, PullSession, PubSession, SubSession的疑问

### ISSUE THREAD

**Issue by coolmian** [q191201771/lal#243]
[官方文档](https://pengrl.com/lal/#/Session)中提到：
====================================
```
A连接B，A向B发送数据：

A | --connect--> | B
  | --av data--> |
上面这种情况：

A属于ClientSession+OutSession，我们称之为PushSession
B属于ServerSession+InSession，我们称之为PubSession
另一种情况，A连接B，B向A发送数据：

A | --connect--> | B
  | <--av data-- |
上面这种情况：

A属于ClientSession+InSession，我们称之为PullSession
B属于ServerSession+OutSession，我们称之为SubSession
```
========================================

我的疑问是：
ServerSession+InSession，为什么叫PubSession？
Publish不应该是发布出去，out的方向吗？

ServerSession+OutSession，为什么叫SubSession？
Subscribe是订阅别人的消息，in的方向

我对PullSession和PushSession的理解没有问题，但是PubSession和SubSession我理解和文档是相反的

**Comment by q191201771** [comment]
首先，这两种理解都没有错，认为一种比另一种好，多少都是带着点主观判断。

你的理解是可能是从动作角度，我的定义是从SFU管理内部角色的角度。
我又想了想，私以为还是我的定义更合理些。

先说你的。
拿subscribe订阅举例，比如我订阅了XX晚报，指的是我先有订阅这个动作，然后别人给我派发XX晚报，有一个主动+被动转换的过程。
你把server+in这种别人主动连接上来、别人主动推数据上来（也即自己完完全全是一个被动者），称之为subscribe订阅，嗯，在我看来多少有点怪，因为无论是发生的事情还是双方的角色都和订阅扯不上一毛钱关系。

再说我的。
上面也提到，我的定义是从SFU管理内部角色的角度，也即在服务端，pub是发布者，sub是订阅者。
在非流媒体领域，pubsub是一种常见的订阅广播服务的场景，大部分时候，服务端也习惯性把发布消息者抽象为pub，订阅者则为sub。

鉴于以上情况，我下了自己的定义，之后在lal相关的领域，都按该规则执行。
专有名词，字面上的可理解性是个该考虑的目标（但不一定达得到），简单、结构化、无二义性才是最重要的，实在不理解就硬背吧。

当一个事物复杂度上升到一定层度，抽象定义必然导致精度丢失，此时你只能要么背，要么翻文档查定义。
想想计算机领域的很多词，都是这样。

**Comment by coolmian** [comment]
> 
谢谢解答！现在我理解了为什么这样定义了以及您说的“主动+被动转换的过程”，但是这样想想似乎不管叫哪种都不太合理了。XD
那我先接受文档这种先固定的叫法吧。
======================================

但是关于这个例子还有疑惑：
“假设服务器上有一场万人演唱会，显然，我们说有一个发布者，一万个订阅者会更好理解一些。”

也就是对应这种情况下：

A | --connect--> | B
  | <--av data-- |

有一万个A在看演唱会，一个B，那么B应该是发布者

**Comment by q191201771** [comment]
一万个人看一个人的演唱会，你愿称之为一个订阅者，一万个发布者吗，XD

**Comment by coolmian** [comment]
> 一万个人看一个人的演唱会，你愿称之为一个订阅者，一万个发布者吗，XD

你可能误会了，我的意思是支持这个例子的表示，但是它与文档描述矛盾了。

\========文档内容========
另一种情况，A连接B，B向A发送数据：

A | --connect--> | B
  | <--av data-- |
上面这种情况：

A属于ClientSession+InSession，我们称之为PullSession
B属于ServerSession+OutSession，我们称之为SubSession
\=======文档内容========

我的理解是：有一万个A在看演唱会，一个B，那么B应该是发布者
但是文档说B是SubSession(订阅)

**Comment by HiveMe** [comment]
@coolmian @q191201771 其实刚看完你俩的讨论，我开始也觉得最后一种情况应该就是PubSession，而不是SubSession，后来我在调试的过程中突然醒悟了，不知道我理解的对不对，所以你们二位看看我这么解释对不对：
首先，Session是服务器为了保存用户状态而创建的一个特殊的对象，它是用来保存用户的状态的。这样以来，无论是pub、sub都是用来保存用户的状态的对象。所以即使是

> 另一种情况，A连接B，B向A发送数据：

A | --connect--> | B
  | <--av data-- |
上面这种情况：

A属于ClientSession+InSession，我们称之为PullSession
B属于ServerSession+OutSession，我们称之为SubSession

即使B属于ServerSession+OutSession，它也是用来保存的用户的session。对于用户来说，这个session就是用于subcribe操作的，所以叫做subsession,其实理解上可以理解为session of subcribe。不知道我这样理解对不对

**Comment by young47** [comment]
从@HiveMe 的角度更容易理解了
