### ISSUE TITLE
建议支持直接rtsp H265的拉流和推流

### ISSUE THREAD

**Issue by kuuyee** [q191201771/lal#25]

**Comment by q191201771** [comment]
master分支已支持接收rtsp h264/h265的推流(rtsp pub h264/h265)。

后续会支持从远端拉取rtsp h264/265的流至本地(rtsp pull h264/h265)，现阶段业务方可通过ffmpeg从远端拉取rtsp流，再转推至lalserver。

**Comment by q191201771** [comment]
> master分支已支持接收rtsp h264/h265的推流(rtsp pub h264/h265)。
> 
> 后续会支持从远端拉取rtsp h264/265的流至本地(rtsp pull h264/h265)，现阶段业务方可通过ffmpeg从远端拉取rtsp流，再转推至lalserver。

除了ffmpeg转推，也可以使用demo中的pullrtsp2pushrtsp进行转推。

**Comment by q191201771** [comment]
这个issue已实现部分：

- rtsp h264/h265
- rtsp pub/sub(lalserver)
- rtsp pull(app/demo)
- rtsp push(app/demo)

只有rtsp relay pull by rtsp(lalserver)没有实现，这个功能后续会支持，移入 #37 管理。
目前这个issue先关闭了，有问题可以随时重新打开或者创建新的issue，感谢。

**Comment by q191201771** [comment]
HTTP-API控制的relay pull回源拉流功能已支持rtsp协议，可以试试，文档见：
https://pengrl.com/lal/#/HTTPAPI?id=_21-apictrlstart_relay_pull
