### ISSUE TITLE
rtsp --> rtmp/http-flv/hls/http-ts 失败

### ISSUE THREAD

**Issue by EricPengShuai** [q191201771/lal#255]
具体来说就是：pub rtsp 可以，pull rtmp/http-flv/hls/http-ts 失败
环境是：windows 1.19版本的 go，最新版本的lal，推流命令：
```bash
ffmpeg -re -stream_loop -1 -i 1-2-Front.mp4 -f rtsp rtsp://127.0.0.1:5544/live/test
```
使用VLC拉流：
```bash
# RTMP 只有声音，ffplay拉流也一样
rtmp://127.0.0.1:1935/live/test

# http-flv 失败，https-flv 也失败，等很久之后可以播放声音？有点疑惑
http://127.0.0.1:8080/live/test.flv

# HLS 也只有声音
http://127.0.0.1:8080/hls/test.m3u8

# http-ts 也只有声音
http://127.0.0.1:8080/live/test.ts
```
VLC 拉取 rtsp 流是正常的，是我配置的问题么

我尝试的 rtmp --> rtsp/hls/http-ts 也有类似问题，只有 rtmp --> http-flv 是正常的

**Comment by q191201771** [comment]
mp4里音频和视频的编码格式是什么？

**Comment by EricPengShuai** [comment]
音频是 AAC，视频是 H264
![Snipaste_2023-02-10_17-31-28](https://user-images.githubusercontent.com/59549218/218055830-8d30632e-dff9-4df3-92bb-6651a1b0bf48.png)

**Comment by q191201771** [comment]
方便的话把mp4文件提供给我，我有空的时候看看。

**Comment by EricPengShuai** [comment]
我这边通过 http_api 接口看到，直接使用上述命令推的话，lal 识别不出来编码格式 acc 和 h264（针对我这个视频，应该是这个原因导致以上问题的），具体来说就是推 rtmp 流无法识别出来 acc 和 h264，推 rtsp 流只能识别出来 acc，所以指定编码格式之后基本上可以正常运行...
```bash
ffmpeg -re -stream_loop -1 -i video.mp4 -vcodec h264 -acodec acc -f flv rtmp://127.0.0.1:1935/live/test

ffmpeg -re -stream_loop -1 -i video.mp4 -vcodec h264 -f rtsp rtsp://127.0.0.1:5544/live/test
```

**Comment by q191201771** [comment]
> https://pan.baidu.com/s/1FpOCHK9SHXW5-1ptfg3UMw?pwd=5djf

是否方便再分享一下，这个地址过期了。
