### ISSUE TITLE
如何实现 pullrtsp subhttpflv

### ISSUE THREAD

**Issue by EricPengShuai** [q191201771/lal#258]
看了看demo，发现好像没有 httpflv sub 的例子，就是目前有一个场景是拉一个服务器的 rtsp 流然后这边提供 http server 服务 sub http flv，最后有一个客户端 flv.js 拉取这个 http-flv 流

刚刚接触这块，不知您这边是否有时间提供一个简单的 sub httpflv 的demo么
> 是不是和这个 issue 有点类似 https://github.com/q191201771/lal/issues/111

**Comment by q191201771** [comment]
Lalserver 支持 relay pull rtsp，并且提供http flv sub能力。
具体看看文档中：

- HTTP-API中的relay pull接口
- http flv的播放方式
