### ISSUE TITLE
rtmp 端口问题

### ISSUE THREAD

**Issue by pandason125** [q191201771/lal#259]
为什么
ffplay rtmp://127.0.0.1/live/test110
和
ffplay rtmp://127.0.0.1:1935/live/test110
两个端口都能拉流播放

**Comment by pandason125** [comment]
> RTMP是Real Time Messaging Protocl（实时传输消息协议）的缩写，它是有Adobe 公司为了Flash播放器和服务器之间进行音频、视频等实时传输而开发的协议；作为一套标准的未加密的实时传输协议，RTMP的默认的传输端口是1935，如果在连接中，未指定传输端口，flash客户端会自动尝试连接其他端口，按照顺序，一次连接1935、443、80等，该协议是建立在TCP或者轮询HTTP协议的基础上的。

RTMPT协议是RTMP协议的变种，此协议的传输是建立在HTTP协议的基础上的，默认端口是80.

 RTMPS协议是经过SSL加密的RMTP协议，增强了数据通信的安全性。

RTMPE 协议也是一个加密版的RTMP协议，不过与RTMPS不同，它采用的不是SSL加密方式，其加密速度快于SSL，且不需要进行认证管理。

RTMPTE协议是一个经过加密通道连接的RTMPE协议，默认端口号是80.

**Comment by q191201771** [comment]
url中省略端口时，会使用默认端口。
rtmp的默认端口是1935。

rtmp://127.0.0.1/live/test110
等价于
rtmp://127.0.0.1:1935/live/test110
