### ISSUE TITLE
建议…可以做一个web后台监管系统

### ISSUE THREAD

**Issue by zkbqhuang** [q191201771/lal#26]
1.实时更新推拉流的客户端数量，ip，带宽流量等
2.分布式集群管理，一键添加或删除流服务器节点
3.实时监控播放正在推流内容，类似于监控室画面
4.根据时间段，播放量等可过滤直播回放视频列表
等等以及其他需要监管的数据信息。

**Comment by q191201771** [comment]
master分支已实现部分HTTP API接口，欢迎使用，并继续提意见，
HTTP API接口对应文档：https://pengrl.com/p/20100/

**Comment by q191201771** [comment]
清理长时间没有处理的issue。这个issue的需求放入 #37 中管理。
有问题可以随时重新打开或创建新的issue。
感谢。
