### ISSUE TITLE
hls拉流如何拉取一段时间内的数据

### ISSUE THREAD

**Issue by Libong** [q191201771/lal#268]
你好,想请问下hls的拉流只有live.m3u8和record.m3u8两种文件吗 好像并没有找到可以获取记录中某一段时间的ts文件 
就好比我需要查看某一段时间内的监控视频

**Comment by q191201771** [comment]
是已经有一堆ts文件，想要找具体的范围吗，这个需要业务方自己做。
方法是通过 HTTP-Notify 的 `on_hls_make_ts` 接口，请参考： https://pengrl.com/#/HTTPNotify?id=_10-on_hls_make_ts

**Comment by Libong** [comment]
ok
