### ISSUE TITLE
jwplayer, hlsjs cannot play hls videos

### ISSUE THREAD

**Issue by testermania** [q191201771/lal#277]
Player Warning 333600. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference#333600

hlsjs does not output an error.

mpv, vlc player no problem for same file.

**Comment by testermania** [comment]
file-1681235116034-1086.ts
file-1681235119953-1087.ts

The stream has correct Access-Control-Allow-Origin headers (CORS)
There are no network errors such as 404s in the browser console when trying to play the stream.

**Comment by q191201771** [comment]
What is the input stream, what protocol is the input stream, and how it is input to lalserver?

**Comment by q191201771** [comment]
How about sending the URL or test file to my email?

191201771@qq.com

**Comment by q191201771** [comment]
Fixed, try it.

**Comment by testermania** [comment]
yes the problem is solved.
