### ISSUE TITLE
stream disconnection issue

### ISSUE THREAD

**Issue by kuabhish** [q191201771/lal#279]
hello @q191201771 

I have seen one problem with the project or may be this is a general problem in rtmp.

Even if the streamer internet is good. the connection is lost a few times. 
Is there any way we can get to the bottom of this like why the tcp connection is lost.

like I know that we get error from here.. 
message2Chunks(https://github.com/q191201771/lal/blob/5983992642c33831eed65e031acadb53cf4a1511/pkg/rtmp/chunk_divider.go#L137)

but my question is more to the tcp thing. that why do we loose connection even if internet is good.

even if the internet is good. why do we see error here.?
how can we ensure that we do not see this error?

Please some help/suggesstion will be appreciated.

**Comment by q191201771** [comment]
Are you using lalserver or your application depending on rtmp package?

**Comment by kuabhish** [comment]
we are using the lal server as the rtmp server.

**Comment by q191201771** [comment]
`  INFO [RTMPPUBSUB1] lifecycle dispose rtmp ServerSession. err=EOF - server_session.go:537`

Check out this line of the log, which points out the reason for the disposed of the session.
e.g. `err=EOF` means the remote side closed it.
