### ISSUE TITLE
rtmp不支持srs中的播放器

### ISSUE THREAD

**Issue by joestarzxh** [q191201771/lal#28]
首先感谢大大提供lal这么好的库；rtmp不支持srs中的播放器http://ossrs.net/players/srs_player.html?app=live&stream=livestream&server=r.ossrs.net&port=1935&autostart=true&vhost=r.ossrs.net
无法播放；主要srs需要AMF3的支持（与AMF0相比前面多加一个0）；回复play之前需要发送StreamIsRecorded，StreamBegin，Connect回复也需要回复AMF3的值.

**Comment by q191201771** [comment]
收到，感谢反馈。
如果你愿意的话，可以给lal项目提PR修复。并在这个issue通知我一下。
否则我会在两周后着手进行修改。
感谢。

**Comment by joestarzxh** [comment]
已提交，你看看

**Comment by q191201771** [comment]
提交的PR已合并进master分支，并且我在此基础上做了一些简单修改。
现在应该是可以播放了。
