### ISSUE TITLE
ffmpeg_push_rtmp_rtsp问题

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#284]
问题1、使用最新lal测试ffmpeg推rtmp到lal，http_ts不能正常工作，相同条件下老版本2022.12.8日下载的lal正常工作
	ffmpeg命令：ffmpeg.exe -stream_loop -1 -re -i source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv -y rtmp://192.168.0.135:1935/live/test
问题2、使用上述2个版本的lal测试ffmpeg推rtsp流到lal，使用flv.js播放器播放http_flv时(它只支持这个)，视频停顿在同一画面音频正常播放，vlc正常播放。
		但是ffmpeg推rtmp流到lal时，使用flv.js播放器播放却是正常的。
		就是push_rtsp和push_rtmp到lal时出来的流可能有区别导致像flv.js这样兼容性不好的播放器出问题。
		ffmpeg.exe -stream_loop -1 -re -i source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv -y rtmp://192.168.0.135:1935/live/test
		ffmpeg.exe -stream_loop -1 -re -i source.200kbps.768x320.flv -vcodec copy -acodec copy -f rtsp rtsp://192.168.0.135:5544/live/test

日志和视频流在附件中：
[lal_quest.zip](https://github.com/q191201771/lal/files/11319307/lal_quest.zip)
忘记上传JS播放器了，这里可以使用，可以把这个网页下载下来本地使用：
https://xqq.im/mpegts.js/demo/

**Comment by q191201771** [comment]
问题1已修复，问题2我在看。

**Comment by q191201771** [comment]
阶段性总结剩余工作项：
rtsp pub的流，使用flv.js播放有问题，具体见上面给的复现方式，以及对应的现象
