### ISSUE TITLE
音频格式问题

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#285]
push_rtsp时使用非AAC的音频格式，比如：mp2，时打印 invalid type
就是不支持音频，拉流时视频可以正常播放。非AAC的音频这种情况
其实对于RTSP/HTTP-TS/HLS来说应该可以支持，只是RTMP/FLV相应
的协议无法做到，pull--RTSP/HTTP-TS/HLS并不强制AAC所以这时应该让
这3种协议正常工作，这样对于无法提供AAC音频的push端至少还能使用这3种协议，
我看ZLMediaKit对于这种情况是支持的，只是未去测试，lal是否考虑支持一下呢。

**Comment by bigbao9494** [comment]
非AAC音频的rtsp_push
	命令：ffmpeg.exe -stream_loop -1 -re -i source.200kbps.768x320.flv -vcodec copy -acodec mp2 -f rtsp rtsp://192.168.0.135:5544/live/test
	ZLMediaKit现象(vlc)：
		rtsp_pull：正常播放音视频，声音正常
		http_ts: 正常播放音视频，静音数据
		http_flv：播放一段时间后停止，静音数据
	lal现象(vlc)：
		rtsp_pull：正常播放视频(add_dummy_audio_enable=false)，无音频数据
		http_ts: 正常播放视频(add_dummy_audio_enable=false)，无音频数据
		http_flv：正常播放视频(add_dummy_audio_enable=true),无法播放(add_dummy_audio_enable=false)

**Comment by q191201771** [comment]
rtsp pub with mp2需要支持rtsp sub播放，并且需要听到声音。
这个已经支持了。
