### ISSUE TITLE
Run as an Adroid Application

### ISSUE THREAD

**Issue by furkanturkmn** [q191201771/lal#287]
I was trying to integrate the server into an android app by generating a library and starting the server through JNI call which is exposed over cgo. Inorder to build the server as a library I was using; CGO_ENABLED=1 GOOS=android GOARCH=arm64 CC=/home/dev/Android-SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang go build -buildmode=c-shared -o libfoo.so main.go as a result the server gets called but somehow it crashes and the android subsystem repeatedly tries to reinitialize the server library. Do you have any clue what the problem might be?

**Comment by q191201771** [comment]
Sorry, I'm not good at Android apps.
Maybe upload the error log to let us have a look.

**Comment by q191201771** [comment]
Sorry, I don't have a clue.
