### ISSUE TITLE
ffmepg rtsp推流的时候，会有两个setup

### ISSUE THREAD

**Issue by BerryCol** [q191201771/lal#288]
![46dfad4b35e87edbb26bb93dcc25243](https://github.com/q191201771/lal/assets/40679211/5cdc94e7-2da4-44d4-8aa5-695a8c19bd9b)

会有两个setup请求，服务端就会开四个udp端口，本地测试发现的，这是ffmepg本地客户端的问题吗

**Comment by q191201771** [comment]
这是正常的。一个setup对应一路音频或一路视频。而一路音频对应两个端口，分别是rtp和rtcp，视频也一样。

**Comment by BerryCol** [comment]
好的，明白了，多谢
