### ISSUE TITLE
OnAvPacket callback

### ISSUE THREAD

**Issue by onthegit** [q191201771/lal#299]
Hello,
thanks for the project.

Is there a way to specify onAvPacket callback? In addition, I could not find a documentation on how to start the RTMP server without config file.

**Comment by q191201771** [comment]
https://github.com/q191201771/lal/blob/master/pkg/rtmp/server.go#L45

```
rtmp.NewServer(":1935", &observer)
```

**Comment by onthegit** [comment]
Hello, thanks for your reply.

Is it possible to determine the FPS from the AVpacket or any other way ?

**Comment by q191201771** [comment]
Basically, FPS=frames / duration time
You can calculate by yourself.
