### ISSUE TITLE
lal设计上的一些疑问

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#3]
这两天看了一下lal代码真的是非常棒的项目，但是也有一些疑问，下面主要是我阅读代码的一些记录疑问在记录当中，这样看起来应该更能表达出我的问题(这些疑问我自己修改后工作正常，见第8点)：

group 创建过程：

    doPublish  -->  func (sm *ServerManager) NewRTMPPubSessionCB
		--> func (sm *ServerManager) getOrCreateGroup(appName string, streamName string)
			根据appName,streamName来判断是否存在，不存在则创建新的group，创建协程执行
                        go group.RunLoop()
			这里有2个疑问：
				group.RunLoop()中无有效动作，只是阻塞等待退出事件 <-group.exitChan，这样设计好
                               像没有意义还浪费一个协程？？
			      难道设计时预留来想专门用这个group协程来执行OnReadRTMPAVMsg处理流数据转发流
                              数据？？但是对OnReadRTMPAVMsg的调用是在NewServerSession协程中直接调用的(没
                              有使用channel，group中也没有创建接收msg的channel)，具体分析见第5点。

    doPlay -->  func (sm *ServerManager) NewRTMPSubSessionCB
			根据appName,streamName来判断是否存在，不存在则创建新的group，创建协程执行
                        go group.RunLoop()
			疑问：
				如果存在group就会对相同group再创建一个协程执行group.RunLoop()，doPublish和
                               doPlay都会生成新协程来执行同一个group的group.RunLoop()，为什么这样设计？？这
                               样会有N+1个协程(N个播放，1个推流)一个播放请求过来会产生3个协程：
                                   代表连接的NewServerSession、connection中专门发数据协程、group中这个阻塞协程
			播放请求时生成的group协程完全是多余的，有处理读数据的NewServerSession和处理写数据
                        的connection协程。

5、	关于 connection 数据写操作：
		当一个流有N个播放端时存在一种情况，推流的ServerSession(对应一个协程)
	需要在收到一个数据时要求极短时间内把数据写入N个connection(通过channel写)，写入后才能接收下一个数据，这个过程是
	同步的所有操作都在同一个ServerSession中完成，也就是ServerSession接收流的协程需要收到chunk数据转成msg再调用OnReadRTMPAVMsg
	来转封装和向N个connection转发数据，播流端的数量和channel的效率会决定推流端的ServerSession能否处理得过来。
	接收推流的协程把chunk转成msg，在OnReadRTMPAVMsg中复制一份msg.Payload，再到broadcastRTMP函数中把msg转成chunk数据。

8、效率修改
	为什么一定要在OnReadRTMPAVMsg中复制一份数据，不复制效率不是更高？？(修改成不复制数据测试正常)
	func (f *FragmentOP) WriteFrame函数中不需要在循环内每次packet := make([]byte, 188)，在循环外或者直接使用成员变量就不用每次去分配内存了。
        group创建过程中提到的协程问题修改后正常工作

**Comment by q191201771** [comment]
##### 1

1.1 group.RunLoop
是的，是为了以后扩展用。老兄可以选择提PR，将go RunLoop调用去掉，但是group内部的相关的逻辑请保留。

1.2 多次go RunLoop
这是一个bug，欢迎老兄提PR修复，将go RunLoop和new group放在一起，或者选择提1.1中的PR。

##### 5

这个我没看出老兄提的问题是啥，貌似是在描述lal的做法，如果有问题可以补充一下。

##### 8

8.1 OnReadRTMPAVMsg数据拷贝

这是因为以下几点：

1. OnReadRTMPAVMsg回调结束后，推流session会复用这个内存，做为下一个msg使用
2. OnReadRTMPAVMsg之后，会异步将这块内存传递给其他拉流session，拉流session在IO可写时，读取这个内存，发送

可以看到，由于第2点读取内存块的时机是不确定的，如果不对内存进行拷贝，那么将造成竞态并发读写。

这里我有考虑过，在推流session中，每个msg都使用一块新的内存，这样OnReadRTMPAVMsg就不用做拷贝了。

但是我们综合来看，假如我只是基于lal写一个rtmp拉流小应用，我对msg的操作只限于回调中，回调结束后不再其他地方持有这块内存块，那么使用目前的复用一块内存块的策略，是一种性能上的优化。

所以，这是一个从两个角度做性能优化的考量。后续我会专门排期针对这些点做bench，并引入内存池，根据结果做优化。

8.2 WriteFrame 188

是的，可以作为FragmentOP的数据成员，欢迎老兄提PR。

另外，老哥，为啥编号直接是5和8。。

**Comment by bigbao9494** [comment]
一、这里我是把我代码阅读记录直接复制上来的，其中有一些是和要问的问题不相关的记录，所以就出现了序号不连续。
二、上面的第5点是关于转发数据自己的理解，是为说清楚doPublish  中产生2个疑问的原因，你再看一下第5点……
三、关于OnReadRTMPAVMsg数据拷贝： 我明白你说的意思和目的，但是程序里面每个推流ServerSession对数据转发现在是同步的，原因就是工在doPublish  中的疑问和第5点对转发数据的分析……

**Comment by bigbao9494** [comment]
PR我晚点做哈，最近工作有点小忙。

**Comment by bigbao9494** [comment]
关于OnReadRTMPAVMsg数据拷贝，单独说更明白一点(直接复制过来的排版可以不好……)：

为什么一定要在OnReadRTMPAVMsg中复制一份数据，不复制效率不是更高？？
		根据第3、6点结论可以得出func (group *Group) OnReadRTMPAVMsg函数调用是同步的，它不依赖
		外部传入的msg，所以不用复制数据(修改成不复制数据测试正常)。

3、func (group *Group) broadcastRTMP(msg rtmp.AVMsg),是RTMP数据转发核心
	group.rtmpSubSessionSet保存所有播放端的RTMP连接
	group.relayPushList所有转推RTMP流
	group.httpflvSubSessionSet保存所有播放httpflv连接
	N个播放端时lcd.Get()中一个MSG只会执行一次rtmp.Message2Chunks
	lcd.Get()把MSG变成chunk(会生成新内存来存放chunk数据),调用session.AsyncWrite 
	--> func (c *connection) write 把数据写入connection，数据写操作具体见第4点
	注意session.AsyncWrite没有处理connection的错误，如果网络不好会丢掉数据(这样设计合理的)。
	为什么说broadcastRTMP是同步的：
		1)、rtmp播放端数据转发和rtmp_relay使用同一个LazyChunkDivider，下面逻辑相同：
		func (lcd *LazyChunkDivider) Get()  -->  func Message2Chunks  -->  defaultChunkDivider.Message2Chunks
		--> func message2Chunks：
			会把OnReadRTMPAVMsg函数中复制的msg转成chunk，out := make([]byte, maxNeededLen)生成新的内存来存储，
			也就是说转发时并未依赖复制出来的那个msg而是使用了新内存。
		2)、httpflv数据转发使用了LazyRTMPMsg2FLVTag：
		func (l *LazyRTMPMsg2FLVTag) Get()  -->  func (t trans) RTMPMsg2FLVTag  -->  func PackHTTPFLVTag:
			同样out := make([]byte, TagHeaderSize+len(in)+prevTagSizeFieldSize)创建新内存复制数据。
		3)、结论：
			group.broadcastRTMP不依赖外部传入/复制出来的这个msg，因为转发时使用了新内存。

6、HLS处理：
	客户端连接处理：
		直接使用http.Server，在函数func (s *Server) ServeHTTP中读取要下载的文件返回给客户端
	TS/m3u8文件生成：
		OnReadRTMPAVMsg --> group.hlsMuxer.FeedRTMPMessage 
			--> func (m *Muxer) feedVideo 实现ES封装成TS并写入文件保存：
				这是一个同步的操作，没有使用协程处理封装和文件写入也没有使用channel传递msg。

**Comment by q191201771** [comment]
OK，懂你的意思，有个细节你可能没注意到，直接把broadcast中的拷贝去掉会出现问题，我补充一下：
**hls中cache的spspps，是直接使用的输入buf，供后续使用，也即可能在本次broadcast后再次读取这块buf，这个地方必须拷贝，**
**建议你提PR时，在package hls的cacheSPSPPS中将数据拷贝一份，然后应该可以把broadcast中的拷贝去除，**

最后总结一下，
rtmp做了一次chunk切割，不持有原有buf，没有问题；
httpflv做转换时，拷贝了一次buf，没有问题；
gop和rtmp，httpflv同理（使用lazy），没有问题；
rtmp relay push同理，没有问题；
hls是同步写，音频数据和视频数据没有问题，
但是缓存sps pps时，需要将数据进行拷贝，
hls中音频adts我也看了下，没有问题，

**Comment by bigbao9494** [comment]
对，SPS_PPS那儿我没有看过，可以按你的意思在cacheSPSPPS时复制需要的数据就可以了。
