### ISSUE TITLE
rtsp没有音频导致推流失败的问题

### ISSUE THREAD

**Issue by snhs163** [q191201771/lal#30]
利用ffmpeg推送NVR的RTSP流，RTSP流视频是H264，没有音频，lalserver接收推流报错，如下图所示：
![image](https://user-images.githubusercontent.com/40191360/94661961-4ecd5c80-033a-11eb-96c3-f5de34ce7877.png)
![9924cf8e5ab0eda7905205a84987a85](https://user-images.githubusercontent.com/40191360/94662365-df0ba180-033a-11eb-8ba6-4025dc0b2aa2.png)

沟通后大致原因是：在lal上做了个音视频重排序，没有音频的流，可能就没法返回了。
请帮忙解决更新下，3Q。

**Comment by q191201771** [comment]
好的，方便的话，再提供一下前面关于SDP信息的日志给我，格式大致是下面这样的。我会尽快修复这个问题，感谢。

```
2020/10/01 19:29:22.648665 DEBUG read http request. method=ANNOUNCE, uri=rtsp://localhost:5544/live/test110, headers=map[CSeq:2 Content-Length:478 Content-Type:application/sdp User-Agent:Lavf57.83.100], body=v=0
o=- 0 0 IN IP6 ::1
s=No Name
c=IN IP6 ::1
t=0 0
a=tool:libavformat 57.83.100
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAFqyyAUBf8uAiAAADAAIAAAMAPB4sXJA=,aOvDyyLA; profile-level-id=640016
a=control:streamid=0
m=audio 0 RTP/AVP 97
b=AS:128
a=rtpmap:97 MPEG4-GENERIC/44100/2
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=121056E500
a=control:streamid=1
 - server.go:92
```

**Comment by snhs163** [comment]
不好意思，这些天有事没来得及看。我把日志贴出来。

\bin>lalserver.exe -c lalserver.conf.json
2020/10/10 20:45:21.459226 [22;37mDEBUG[0m 1528 - handshake.go:291
2020/10/10 20:45:21.480168 [22;36m INFO[0m load conf file succ. file=lalserver.conf.json content=&{RTMPConfig:{Enable:true Addr::19350 GOPNum:2} HTTPFLVConfig:{ServerConfig:{Enable:true SubListenAddr::8080 EnableHTTPS:false HTTPSAddr::4433 HTTPSCertFile:./conf/cert.pem HTTPSKeyFile:./conf/key.pem} GOPNum:2} HLSConfig:{SubListenAddr::8081 MuxerConfig:{Enable:true OutPath:/tmp/lal/hls/ FragmentDurationMS:3000 FragmentNum:6}} HTTPTSConfig:{Enable:true SubListenAddr::8082} RTSPConfig:{Enable:true Addr::5544} RelayPushConfig:{Enable:false AddrList:[]} RelayPullConfig:{Enable:false Addr:} PProfConfig:{Enable:true Addr::10001} LogConfig:{Level:1 Filename:./logs/lalserver.log IsToStdout:true IsRotateDaily:true ShortFileFlag:true AssertBehavior:1}} - entry.go:56
2020/10/10 20:45:21.480168 [22;36m INFO[0m initial log succ. - entry.go:67
2020/10/10 20:45:21.480168 [22;36m INFO[0m bininfo: GitTag=v0.15.1. GitCommitLog=ed5471e74504b61e91da43f6f73dcb52b4013fe3 v0.15.1. GitStatus=cleanly. BuildTime=2020.09.19.224735. GoVersion=go version go1.14.2 darwin/amd64. runtime=windows/amd64. - entry.go:31
2020/10/10 20:45:21.481165 [22;36m INFO[0m version: lal v0.15.1 (github.com/q191201771/lal) - entry.go:32
2020/10/10 20:45:21.481165 [22;36m INFO[0m start web pprof listen. addr=:10001 - entry.go:71
2020/10/10 20:45:21.484158 [22;36m INFO[0m start rtmp server listen. addr=:19350 - server.go:41
2020/10/10 20:45:21.485155 [22;36m INFO[0m start httpflv server listen. addr=:8080 - server.go:57
2020/10/10 20:45:21.486154 [22;36m INFO[0m start httpts server listen. addr=:8082 - server.go:42
2020/10/10 20:45:21.486154 [22;36m INFO[0m start hls server listen. addr=:8081 - server.go:39
2020/10/10 20:45:21.486154 [22;36m INFO[0m start rtsp server listen. addr=:5544 - server.go:60
2020/10/10 20:45:26.359913 [22;37mDEBUG[0m > handleTCPConnect. conn=0xc0000061b0 - server.go:84
2020/10/10 20:45:26.369887 [22;37mDEBUG[0m read http request. method=OPTIONS, uri=rtsp://localhost:5544/live/test111, headers=map[CSeq:1 User-Agent:Lavf58.35.101], body= - server.go:92
2020/10/10 20:45:26.369887 [22;36m INFO[0m < R OPTIONS - server.go:97
2020/10/10 20:45:26.370890 [22;37mDEBUG[0m read http request. method=ANNOUNCE, uri=rtsp://localhost:5544/live/test111, headers=map[CSeq:2 Content-Length:290 Content-Type:application/sdp User-Agent:Lavf58.35.101], body=v=0
o=- 0 0 IN IP6 ::1
s=HIK Media Server V3.4.109
c=IN IP6 ::1
t=0 0
a=tool:libavformat 58.35.101
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z00AHo2NQFAX/LCAAAOEAACvyAI=,aO44gA==; profile-level-id=4D001E
a=control:streamid=0
 - server.go:92
2020/10/10 20:45:26.372879 [22;36m INFO[0m < R ANNOUNCE - server.go:102
2020/10/10 20:45:26.372879 [22;36m INFO[0m [RTSP1] lifecycle new rtsp PubSession. session=0xc000190820, streamName=test111 - server_pub_session.go:62
2020/10/10 20:45:26.372879 [22;36m INFO[0m [GROUP1] lifecycle new group. appName=, streamName=test111 - group.go:76
2020/10/10 20:45:26.373876 [22;37mDEBUG[0m [GROUP1] [RTSP1] add RTSP PubSession into group. - group.go:200
2020/10/10 20:45:26.373876 [22;36m INFO[0m [HLSMUXER1] lifecycle new hls muxer. muxer=0xc0001980e0, streamName=test111 - muxer.go:102
2020/10/10 20:45:26.373876 [22;36m INFO[0m [HLSMUXER1] start hls muxer. - muxer.go:107
2020/10/10 20:45:26.376869 [22;37mDEBUG[0m read http request. method=SETUP, uri=rtsp://localhost:5544/live/test111/streamid=0, headers=map[CSeq:3 Transport:RTP/AVP/UDP;unicast;client_port=25566-25567;mode=record User-Agent:Lavf58.35.101], body= - server.go:92
2020/10/10 20:45:26.376869 [22;36m INFO[0m < R SETUP - server.go:135
2020/10/10 20:45:26.377865 [22;37mDEBUG[0m acquire udp conn. rtp port=8000, rtcp port=8001 - server.go:165
2020/10/10 20:45:26.378865 [22;37mDEBUG[0m RTP/AVP/UDP;unicast;client_port=25566-25567;mode=record - pack.go:120
2020/10/10 20:45:26.379862 [22;37mDEBUG[0m read http request. method=RECORD, uri=rtsp://localhost:5544/live/test111, headers=map[CSeq:4 Range:npt=0.000- Session:191201771 User-Agent:Lavf58.35.101], body= - server.go:92
2020/10/10 20:45:26.379862 [22;36m INFO[0m < R RECORD - server.go:173
2020/10/10 20:45:31.127764 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.160677 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.204558 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.237470 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.281353 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.325235 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.358148 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.402030 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.445912 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.478824 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.486804 [22;37mDEBUG[0m group size=1 - server_manager.go:135
2020/10/10 20:45:31.486804 [22;37mDEBUG[0m [GROUP1] stream name=test111, rtmp pub=RTSP1, relay rtmp pull=none, rtmp sub=0, httpflv sub=0, httpts sub=0, relay rtmp push=0 - server_manager.go:137
2020/10/10 20:45:31.522707 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.566589 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.599501 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.643384 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57
2020/10/10 20:45:31.687270 [22;33m WARN[0m video queue full, drop front packet. - avpacket_queue.go:57

**Comment by q191201771** [comment]
rtsp pub推流，纯视频（没有音频）流处理失败的问题，
已修复，代码已提交至master分支，你测试看看，
感谢，

**Comment by q191201771** [comment]
这个bug之前已经修复了，这个issue太久先关闭了。
如果还有问题可以随时重新打开或者创建新的issue，感谢。
