### ISSUE TITLE
Cannot play HLS stream on browser

### ISSUE THREAD

**Issue by nilopaim** [q191201771/lal#301]
I think the problem is not directly related to LAL, but anyway I'm asking for some help...

I'm using LAL to capture live streaming from camera and mic and pushing and serving the stream to/from my internet server.

The streaming is captured and shown without any issues using VLC or browser HLS plugins. But when I try hls.js on my HTML page (without plugins) to show the streaming I got a message from hls.js saying "ManifestParsingError".

Am I missing some detail to make this work? Are there some HTML sample page that I can examine and could play my stream? Can you recommend some another HTML HLS player?

By the way, LAL is an extraordinary piece of software! Congratulations!

**Comment by q191201771** [comment]
https://v2.h5player.bytedance.com/generate/

**Comment by nilopaim** [comment]
Nice link, but it doesn't play my stream either...

I'm still thinking that my problem is not directly related to LAL, but...

Thanks for your answer.

**Comment by q191201771** [comment]
How about trying to test FFmpeg instead of LAL stuff?

**Comment by nilopaim** [comment]
Thanks for your comment.

As I told you before, my problem wasn't related to LAL.

The problem was in the configuration of my server. When solved, all the streams generated by LAL works like a charm!

Thanks a lot for your interest and congratulations for LAL! Fantastic software!
