### ISSUE TITLE
原始流转推多个链接（二次开发）

### ISSUE THREAD

**Issue by fpf-Titan** [q191201771/lal#302]
请问，原始流转推（广播）多个CDN时，如何根据不同的CDN地址采用不同的加密方式呢？

**Comment by q191201771** [comment]
你是使用lalserver做二次开发吗？还是其他方式？

**Comment by fpf-Titan** [comment]
感谢回复，对我是使用lalserver做的二次开发，目前加密是放在broadcastByRtmpMsg(msg base.RtmpMsg)函数中的，但是内部无法区分当前转发的CDN地址，请问有什么建议吗？
