### ISSUE TITLE
重复的Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by czlin** [q191201771/lal#309]
通过hls拉流m3u8 接口会默认添加Access-Control-Allow-Origin：*，
但是我通过ngingx转发也会给这个接口加上自己的Access-Control-Allow-Origin。会导致头部重复，请问如何去掉lal自带的Access-Control-Allow-Origin。
<img width="979" alt="image" src="https://github.com/q191201771/lal/assets/9177693/8078f246-e722-4b57-8ec5-801f9d011d02">

![image](https://github.com/q191201771/lal/assets/9177693/3b3fbcd7-f3aa-47e8-8725-c4f8b7619979)

**Comment by q191201771** [comment]
我在最新代码里新增加了一个变量 AddCors2HlsFlag ( https://github.com/q191201771/lal/blob/master/pkg/base/var.go#L16 )
该变量设置为false时就不会为hls增加CAccess-Control-Allow-Origin头信息了。

你可以在main函数的起始位置 ( 如果你使用的是原生的 app/lalserver，那么对应的位置是 https://github.com/q191201771/lal/blob/master/app/lalserver/main.go#L23 ) 设置该变量：

`base.AddCors2HlsFlag = false`

另外，使用上面的代码你需要确保已引入package base，例如：

`import "github.com/q191201771/lal/pkg/base"`

**Comment by czlin** [comment]
已解决，谢谢
