### ISSUE TITLE
rtsp 无法推流

### ISSUE THREAD

**Issue by czlin** [q191201771/lal#311]
使用推流命令 
`ffmpeg -rtsp_transport tcp -re -stream_loop -1 -y -i rtsp://admin:admin@192.168.13.247:554/stream1 -c:v copy -f flv rtmp://192.168.14.12:1935/live/tplink`

ffmpeg 输出如下日志：

> ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04.1)
  configuration: --prefix=/usr/local/ffmpeg/ --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --extra-libs='-lpthread -lm' --bindir=/usr/local/ffmpeg/bin --enable-shared --enable-ffplay --enable-cuda --enable-cuvid --enable-nvenc --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://admin:admin@192.168.13.247:554/stream1':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.033333, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac, 48000 Hz, stereo, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help

lal 日志：

> 2023/08/21 18:19:41.964448  INFO accept a rtmp connection. remoteAddr=192.168.14.12:46206 - server.go:95
2023/08/21 18:19:41.964552 DEBUG [NAZACONN2] lifecycle new connection. net.Conn=0xc0001be328, naza.Connection=0xc0001de630 - connection.go:193
2023/08/21 18:19:41.964597  INFO [RTMPPUBSUB2] lifecycle new rtmp ServerSession. session=0xc0002a44e0, remote addr=192.168.14.12:46206 - server_session.go:113
2023/08/21 18:19:41.964727 DEBUG handshake complex mode. - handshake.go:248
2023/08/21 18:19:41.964802  INFO [RTMPPUBSUB2] < R Handshake C0+C1. - server_session.go:197
2023/08/21 18:19:41.964824  INFO [RTMPPUBSUB2] > W Handshake S0+S1+S2. - server_session.go:199
2023/08/21 18:19:41.965104  INFO [RTMPPUBSUB2] < R Handshake C2. - server_session.go:207
2023/08/21 18:19:42.008563  INFO [RTMPPUBSUB2] < R connect('live'). tcUrl=rtmp://192.168.14.12:1935/live - server_session.go:413
2023/08/21 18:19:42.008627  INFO [RTMPPUBSUB2] > W Window Acknowledgement Size 5000000. - server_session.go:417
2023/08/21 18:19:42.008724  INFO [RTMPPUBSUB2] > W Set Peer Bandwidth. - server_session.go:422
2023/08/21 18:19:42.008823  INFO [RTMPPUBSUB2] > W SetChunkSize 4096. - server_session.go:427
2023/08/21 18:19:42.008910  INFO [RTMPPUBSUB2] > W _result('NetConnection.Connect.Success'). - server_session.go:432
2023/08/21 18:19:42.052620 DEBUG [RTMPPUBSUB2] read command message, ignore it. cmd=releaseStream, header={Csid:3 MsgLen:35 MsgTypeId:20 MsgStreamId:0 TimestampAbs:0}, b=len(core)=128, rpos=25, wpos=35, hex=00000000  05 02 00 06 74 70 6c 69  6e 6b                    |....tplink|
 - server_session.go:366
2023/08/21 18:19:42.052680 DEBUG [RTMPPUBSUB2] read command message, ignore it. cmd=FCPublish, header={Csid:3 MsgLen:31 MsgTypeId:20 MsgStreamId:0 TimestampAbs:0}, b=len(core)=128, rpos=21, wpos=31, hex=00000000  05 02 00 06 74 70 6c 69  6e 6b                    |....tplink|
 - server_session.go:366
2023/08/21 18:19:42.052703  INFO [RTMPPUBSUB2] < R createStream(). - server_session.go:444
2023/08/21 18:19:42.052721  INFO [RTMPPUBSUB2] > W _result(). - server_session.go:445
2023/08/21 18:19:42.096516 DEBUG [RTMPPUBSUB2] pubType=live - server_session.go:474
2023/08/21 18:19:42.096565  INFO [RTMPPUBSUB2] < R publish('tplink') - server_session.go:475
2023/08/21 18:19:42.096585  INFO [RTMPPUBSUB2] > W onStatus('NetStream.Publish.Start'). - server_session.go:477
2023/08/21 18:19:42.096816  INFO [GROUP2] lifecycle new group. group=0xc0002ba380, appName=live, streamName=tplink - group__.go:185
2023/08/21 18:19:42.096856 DEBUG [GROUP2] [RTMPPUBSUB2] add rtmp pub session into group. - group__in.go:59
2023/08/21 18:19:42.099315 DEBUG [RTMP2MPEGTS2] NewRtmp2MpegtsRemuxer - rtmp2mpegts.go:117
2023/08/21 18:19:42.099374 DEBUG [GROUP2] [RTMP2MPEGTS2] NewRtmp2MpegtsRemuxer in group. - group__in.go:357
2023/08/21 18:19:42.099457  INFO [HLSMUXER2] lifecycle new hls muxer. muxer=0xc00016c000, streamName=tplink - muxer.go:116
2023/08/21 18:19:42.099485  INFO [HLSMUXER2] start hls muxer. - muxer.go:121
2023/08/21 18:19:52.100111 DEBUG [NAZACONN2] close once. err=read tcp 10.110.6.3:1935->192.168.14.12:46206: i/o timeout - connection.go:509
2023/08/21 18:19:52.100325  INFO [RTMPPUBSUB2] lifecycle dispose rtmp ServerSession. err=read tcp 10.110.6.3:1935->192.168.14.12:46206: i/o timeout - server_session.go:549
2023/08/21 18:19:52.100396 DEBUG [NAZACONN2] Close. - connection.go:381
2023/08/21 18:19:52.100426 DEBUG [GROUP2] [RTMPPUBSUB2] del rtmp PubSession from group. - group__in.go:318
2023/08/21 18:19:52.100449  INFO [HLSMUXER2] lifecycle dispose hls muxer. - muxer.go:126
2023/08/21 18:19:52.866257  INFO erase inactive group. [GROUP2] - server_manager__.go:302
2023/08/21 18:19:52.866313  INFO [GROUP2] lifecycle dispose group. - group__.go:222
2023/08/21 18:19:52.866343 DEBUG DEBUG_GROUP_LOG: group size=0 - server_manager__.go:315
2023/08/21 18:19:56.357774  INFO cleanup hls file path. streamName=tplink, path=lal_record/hls/tplink - server_manager__.go:744

过了大概1分钟，ffmpeg 报错：

> [vost#0:0/copy @ 0x557a62f24980] Too many packets buffered for output stream 0:0.
[vost#0:0/copy @ 0x557a62f24980] Error submitting a packet to the muxer
[vost#0:0/copy @ 0x557a62f24980] Too many packets buffered for output stream 0:0.
[vost#0:0/copy @ 0x557a62f24980] Error submitting a packet to the muxer
[vost#0:0/copy @ 0x557a62f24980] Too many packets buffered for output stream 0:0.
[vost#0:0/copy @ 0x557a62f24980] Error submitting a packet to the muxer

**Comment by q191201771** [comment]
把你的命令：

`ffmpeg -rtsp_transport tcp -re -stream_loop -1 -y -i rtsp://admin:admin@192.168.13.247:554/stream1 -c:v copy -f flv rtmp://192.168.14.12:1935/live/tplink`

修改为以下两个命令：

`ffmpeg -rtsp_transport tcp -re -stream_loop -1 -y -i rtsp://admin:admin@192.168.13.247:554/stream1 -c:v copy -c:a copy -f flv rtmp://192.168.14.12:1935/live/tplink`

`ffmpeg -rtsp_transport tcp -re -stream_loop -1 -y -i rtsp://admin:admin@192.168.13.247:554/stream1 -c:v copy -an -f flv rtmp://192.168.14.12:1935/live/tplink`

再分别测试一下。

**Comment by czlin** [comment]
使用第一条命令可以了。感谢大佬。
