### ISSUE TITLE
推送http_ts流的客户端

### ISSUE THREAD

**Issue by hnmaonanbei** [q191201771/lal#32]
你好：
        万分期望您在app/demo下添加ts流推送至lal-server的demo

**Comment by q191201771** [comment]
你好：
目前lal仅支持从lal-server拉取http-ts流，并不支持推送http-ts流。
我之前没有了解过http-ts推流，请问你是什么场景下需要？
或者现在是否有开源或常见的客户端、服务端支持http-ts推流？
请提供更多信息给我，我很乐意实现更多的功能。

**Comment by hnmaonanbei** [comment]
yo 您好：
     目前我已经跳过了这个问题,不过我有遇到了一个新的问题。

**Comment by hnmaonanbei** [comment]
yo 您好：
          十分感激您的回复, 题中的需求已经解决了，并成功的使用的lal-server的部分库

**Comment by hnmaonanbei** [comment]
yo 您好：
十分感激您的回复, 题中的需求已经解决了，并成功的使用的lal-server的部分库

**Comment by hnmaonanbei** [comment]
yo 您好：
十分感激您的回复, 题中的需求已经解决了，并成功的使用的lal-server的部分库。 有一点不太成熟的建议，比如flv解析库，建议将*os.File类型 改成 io 接口类型，这样用起来就不需要改源码了。

**Comment by q191201771** [comment]
感谢提出宝贵建议。

你说的flv解析与*os.File，指的是`flv_file_reader.go`吗？
目前，
`flv_file_reader.go`对应读取flv文件，
`client_pull_session.go`对应拉取http-flv流，
它们都依赖更底层的解析flv tag的函数，
因为除了这两个场景，我还没有遇到其他读取flv流的场景，
所以`flv_file_reader.go`写的比较固定，直接包含了打开文件的操作，使得上层使用简单些。

后续有其他使用上的问题，欢迎继续提issue。
