### ISSUE TITLE
hls 流 ID 获取不准确

### ISSUE THREAD

**Issue by ixugo** [q191201771/lal#320]
## 问题
hls 播放有两种方式
`http://localhost:8080/hls/<streamID>.m3u8 `
`http://localhost:8080/hls/<streamID>/playlist.m3u8`
后者的播放，在 `/api/stat/group` 接口中会导致产生 流 ID 不一样，根据上面图片中的函数，后者拿到的 流 id 是 `playlist.m3u8`。

导致 sub 统计的数据不准确。

![image](https://github.com/q191201771/lal/assets/59127546/40d2e57b-315e-4a80-882c-3973e0d31f07)

![image](https://github.com/q191201771/lal/assets/59127546/f3c9dcc8-26dc-4297-8ffc-f1dc7b49306d)

**Comment by q191201771** [comment]
感谢PR，已经merge了。
