### ISSUE TITLE
【开脑洞】用go直接编写移动端的推拉流库

### ISSUE THREAD

**Issue by zkbqhuang** [q191201771/lal#34]
gomobile可将go程序编译成Android和iOS库，gomobile安装和使用比较容易，具体可参考。
https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-android-1
这样就可以在服务端和客户端共用一些相同功能性的代码，比如rtmp等数据流的解析，传输处理。这样整体项目的整体性更好。也将go语言的便捷性使用扩大，替代C/C++编写移动底层库，降低编译和使用难度。

这边推荐一个im类型项目，它的Android客户端就是这么干的，gomobile编译出.aar给Android使用，可供参考。
https://github.com/dearcode/candy

当然这只是个建议，还不知道是否真的可行，大神有兴趣可以尝试尝试！

**Comment by q191201771** [comment]
哈哈，开开脑洞挺好，不过暂时没时间看了，先标记在这吧。
