### ISSUE TITLE
能否增加动态拉取H264/H265 RTSP流!

### ISSUE THREAD

**Issue by leotian111** [q191201771/lal#35]
能否增加在访问httpflv流时, 当对应流不存在时能动态去拉取H264/H265 RTSP流! 拉取成功后让刚刚请求的httpflv流能播放;
然后增加hook接口: OnStreamNotFound --当请求httpflv流不存在时触发, 然后让客户去拉流;  OnPlay--给客户机会检查token;  OnStreamNoneReader--当没有读者时,给客户自己决定是否关闭刚刚拉取的RTSP流. 多谢!

**Comment by q191201771** [comment]
目前只支持RTMP pull回源，不支持RTSP pull回源，会尽快添加支持。

OnStreamNotFound：目前有on_sub_start，里面有当前是否存在输入流的标志，供业务方判断。
OnPlay token：这个是做拉流鉴权吗？后续会提供关闭指定流的HTTP API，业务方可实现异步拉流鉴权。
OnStreamNoneReader：目前当没有读者时，lalserver会关闭对应的pull回源。这种固定的关闭模式，是否满足你的需求？

**Comment by leotian111** [comment]
OnStreamNoneReader可以, 一般默认的也是关闭!   OnPlay token是对httpflv用户端的签权, 不是rtsp拉流时的签权

**Comment by q191201771** [comment]
嗯，目前httpflv sub(播放者)的url参数会通过HTTP Notify回调给业务方。
后面加一个HTTP API，用来命令lalserver关闭指定的sub，就可以实现异步鉴权了。

**Comment by leotian111** [comment]
好的, 期待您的好消息!

**Comment by q191201771** [comment]
关闭指定sub的HTTP API已经支持了。
rtsp pull回源还不支持。这个功能移入 #37 这个issue中统一管理。
这个issue太久先关闭了。有问题可随时重新打开这个issue或者创建新的issue，感谢。

**Comment by q191201771** [comment]
HTTP-API控制的relay pull回源拉流功能已支持rtsp协议，可以试试，文档见：
https://pengrl.com/lal/#/HTTPAPI?id=_21-apictrlstart_relay_pull
