### ISSUE TITLE
rtmp花屏

### ISSUE THREAD

**Issue by xianghan228** [q191201771/lal#38]
push with rtsp, and pull use rtmp , 花屏，感觉新来的rtmp流第一帧不是关键帧

**Comment by q191201771** [comment]
应该是rtsp pub推流时，rtp over udp发生丢包导致的。

花屏的根本原因在于上层：

1. 没有丢弃不完整帧所属GOP剩余帧的逻辑（但是会丢弃不完整帧，也即会花屏，但是也会保证流的合法与协议栈不出错）
2. 没有等关键帧的逻辑

因为之前考虑RTMP类型的流比较多，预设条件是输入的流都是没问题的。
出于逻辑简单和性能方面的考虑，少了一些逻辑。

我后续会修复这个Bug，请保留这个issue打开，我修复完会在此回复，感谢。

**Comment by q191201771** [comment]
该问题移入 #37 管理，这个issue先关闭了，有问题可随时重新打开或创建新的issue，感谢。
