### ISSUE TITLE
 WARN [HLSMUXER117] force fragment split.

### ISSUE THREAD

**Issue by xoraingroup** [q191201771/lal#40]
Hls fragments stopped after alot of warnings.

 WARN [HLSMUXER117] force fragment split. fragTS=5887080, ts=32262660 - muxer.go:197

```bash
2020/12/10 06:17:04.654147  WARN [HLSMUXER117] force fragment split. fragTS=220818150, ts=100316700 - muxer.go:197
2020/12/10 06:17:04.655346  WARN [HLSMUXER117] force fragment split. fragTS=100316700, ts=220822020 - muxer.go:197
2020/12/10 06:17:04.656969  WARN [HLSMUXER117] force fragment split. fragTS=220822020, ts=100319760 - muxer.go:197
2020/12/10 06:17:04.658761  WARN [HLSMUXER117] force fragment split. fragTS=100319760, ts=220825800 - muxer.go:197
2020/12/10 06:17:04.660818 DEBUG naza connection close. err=EOF, conn=0xc0000b8140 - connection.go:405
2020/12/10 06:17:04.660855  INFO [RTMPPUBSUB336] rtmp loop done. err=EOF - server.go:69
2020/12/10 06:17:04.660860 DEBUG naza connection recv exitChan and exit write loop. conn=0xc0000b8140 - connection.go:367
2020/12/10 06:17:04.660863 DEBUG [GROUP116] [RTMPPUBSUB336] del rtmp PubSession from group. - group.go:653
2020/12/10 06:17:04.660874  INFO [HLSMUXER117] lifecycle dispose hls muxer. - muxer.go:110
```

**Comment by q191201771** [comment]
The log shows that the timestamp was jumping(back and forward alternately).

I guess maybe the timestamp of the input audio and video are not in the same baseline.

Which protocol type of input do you use?

**Comment by xoraingroup** [comment]
Input type is rtmp.

**Comment by q191201771** [comment]
> Your log shows that the timestamp was jumping(back and forward alternately).
> I guess maybe the timestamp of the input audio and video are not in the same baseline.

You can turn on a debug log to see if the timestamp of input RTMP audio and video are jumping.
debug log: https://github.com/q191201771/lal/blob/master/pkg/rtmp/chunk_composer.go#L113

If so, this type of input stream is invalid, maybe you should check the RTMP push client.

when jumping too large, HLS will force reopen a ts file.
each of the under situations will be considered as jumping too large:

1. jump forward: > one ts file duration(fragment_duration_ms, which config by config file) * 10
2. jump back: > 1 sec

see: https://github.com/q191201771/lal/blob/master/pkg/hls/muxer.go#L196

**Comment by q191201771** [comment]
Close this issue since timeout.
Feel free to reopen it if needed.
