### ISSUE TITLE
rtmp拉流问题（部分rtmp出错）

### ISSUE THREAD

**Issue by lei006** [q191201771/lal#42]
在拉流 rtmp://218.3.205.46/live/xwzh_sd 时候显示错误: 

PS D:\Work\fork\lal> go run .\app\demo\pullrtmp\pullrtmp.go -i rtmp://218.3.205.46/live/xwzh_sd -o jnxw_sd.flv       
2020/12/25 19:47:30.077850  INFO [RTMPPULL1] lifecycle new rtmp ClientSession. session=0xc000146000 - client_session.go:102
2020/12/25 19:47:30.082881  INFO [RTMPPULL1] > W Handshake C0+C1. - client_session.go:271
2020/12/25 19:47:36.124649 DEBUG naza connection close. err=EOF, conn=0xc00018a000 - connection.go:405
**2020/12/25 19:47:36.131628 ERROR assert failed. excepted=<nil>, but actual=lal.rtmp: client session timeout - pullrtmp.go:91**
2020/12/25 19:47:36.132639 DEBUG EOF - pullrtmp.go:93

**Comment by q191201771** [comment]
好的，看起来是rtmp握手的问题，知道对端服务器用啥搭建的吗，是开源的吗，

**Comment by q191201771** [comment]
问题已经修复了，方便可以帮忙测试一下，感谢。

**Comment by q191201771** [comment]
这个问题已经修复，这个issue先关闭了。
有问题可以随时重新打开或者创建新的issue，感谢。
