### ISSUE TITLE
读取rtsp转发到rtstp服务器

### ISSUE THREAD

**Issue by lx37506** [q191201771/lal#43]
最近项目需要将摄像头的rtsp图像读取出来转发至云端rtsp服务器。希望您可以添加这部分功能谢谢！

**Comment by q191201771** [comment]
已支持，见master分支最新代码下的`app/demo/pullrtsp2pushrtsp/`，欢迎继续反馈。

**Comment by q191201771** [comment]
这个需求已经支持，这个issue先关闭了，有问题可以随时重新打开或创新新的issue，感谢。
