### ISSUE TITLE
v0.19.0程序会卡死

### ISSUE THREAD

**Issue by ChungTak** [q191201771/lal#45]
### 测试环境
- 系统: ubuntu 20.04 
- 内存:16G
- CPU: 4.01 GHz 四核Intel Core i7
- 网络： 127.0.0.1本地循环网络
- 测试客户端：srs-bench
- 测试版本：lal_v0.19.0_linux从release中下载。参数修改:"gop_num": 0 和关闭 hls
- 测试方法：推流1路，通过srs-bench  播放100路RTMP
srs-bench推流命令：`srs-bench/objs/sb_rtmp_publish -i doc/source.200kbps.768x320.flv -c 1 -r rtmp://127.0.0.1:1935/live/livestream 
srs-bench压测命令:`srs-bench/objs/sb_rtmp_load -c 100 -r rtmp://127.0.0.1:1935/live/livestream`
### 出现问题
- ffplay 直接播放一路没有问题.
- srs-bench 加载完100路几秒后，推流端和播放端就会卡住。使用ffplay播放不了，像是死锁的感觉，程序没有崩溃。
- srs-bench 有时候压测10路都会出现
- lal_v0.18.0_linux 版本不会出现

**Comment by q191201771** [comment]
感谢反馈，并提供了丰富的问题描述。
我已经修复了这个bug，并发布了新的release版本。
请可以下载v0.19.1中的可执行文件进行验证。

具体修改见：https://github.com/q191201771/lal/commit/5993af7456e2046566face4512eb9af294621d4d
在v0.19.0基础发布的v0.19.1版本：https://github.com/q191201771/lal/releases/tag/v0.19.1

再次感谢。

**Comment by ChungTak** [comment]
非常棒！问题已经修复～～但还发现其他问题～

1.播放不了rtsp,推流地址 `rtmp://127.0.0.1:1935/live/livestream`
` ffplay  rtsp://localhost:5544/live/livestream
`
日志错误信息如下：
[rtsp播放出错日志.log](https://github.com/q191201771/lal/files/5907767/rtsp.log)

 2.ffmpeg推流添加时间戳，hls目录没有生成文件，rtmp播放没问题.日志没异常
测试推流命令：
`ffmpeg -stream_loop -1 -re -i "source.200kbps.768x320.flv" -vf "settb=AVTB,
            setpts='trunc(PTS/1K)*1K+st(1,trunc(RTCTIME/1K))-1K*trunc(ld(1)/1K)',
            drawtext=fontsize=14:fontcolor=black:text='%{localtime}.%{eif\:1M*t-1K*trunc(t*1K)\:d}'" -an -f flv rtmp://127.0.0.1:1935/live/livestream`

**Comment by q191201771** [comment]
1.
目前不支持rtmp pub -> rtsp sub
只支持
rtsp pub -> rtsp sub
rtsp pub -> rtmp sub
也即rtsp只能播放rtsp的推流，rtsp的推流可以转换成其他格式的拉流。
你说的这个以后会实现。

2.
我简单测试了一下，没有复现问题，你再确定一下hls功能是否开启了。
如果还是不行，把日志贴一下。

感谢。
