### ISSUE TITLE
RTSP转RTMP压测崩溃

### ISSUE THREAD

**Issue by ChungTak** [q191201771/lal#47]
### 测试环境
- 系统: ubuntu 20.04 
- 内存:16G
- CPU: 4.01 GHz 四核Intel Core i7
- 网络： 127.0.0.1本地循环网络
- 测试客户端：srs-bench
- 测试版本：lal_v0.19.1_linux从release中下载。默认参数
### 重现步骤
- rtsp推流使用udp或者tcp方式都可以
`ffmpeg -re -stream_loop -1 -i "bbb_sunflower_1080p_30fps_normal.mp4" -an -vcodec copy -rtsp_transport tcp -f rtsp rtsp://localhost:5544/live/livestream`
- srs-bench压测500路，等待全部加载完成。然后 srs-bench 界面ctrl+c 结束压测，出现崩溃。压测100路不会出现，有时候压测1000路，加载过程中直接崩溃。崩溃都是同一个异常，不太懂代码，看上去是map并发问题。
`sb_rtmp_load -c 1000 -r rtmp://127.0.0.1:1935/live/livestream`
错误日志:
`fatal error: concurrent map iteration and map write2021/03/18 12:12:13.671875 DEBUG [GROUP1] [RTMPPUBSUB75] del rtmp SubSession from group. - group.go:668`
[lal.log](https://github.com/q191201771/lal/files/6161267/lal.log)

**Comment by ChungTak** [comment]
[lalserver.log](https://github.com/q191201771/lal/files/6161286/lalserver.log)
补上服务器log，没有打印出错误

**Comment by q191201771** [comment]
感谢提出问题。
我尝试修复了这个问题，你可以使用附件中的执行程序（或拉取master分支的最新代码）进行测试。
欢迎继续反馈。

[lalserver.zip](https://github.com/q191201771/lal/files/6215677/lalserver.zip)

**Comment by ChungTak** [comment]
master分支没问题，效果很棒～
