### ISSUE TITLE
HLS文件存取方式问题

### ISSUE THREAD

**Issue by chinatsm** [q191201771/lal#50]
请问大神，这个项目能否加一个内存储取，减少磁盘IO的功能

**Comment by q191201771** [comment]
好的，会排期开发。

**Comment by q191201771** [comment]
master分支的最新代码已支持hls内存切片。见配置文件中的配置项`use_memory_as_disk_flag`
配置文件说明见： https://pengrl.com/lal/#/ConfigBrief

**Comment by chinatsm** [comment]
Tried it, very good
