### ISSUE TITLE
http类型的协议（flv，ts，hls）支持绑定相同的端口

### ISSUE THREAD

**Issue by q191201771** [q191201771/lal#64]
使得业务方使用更灵活，比如都使用80端口，通过path路径区分协议。

**Comment by q191201771** [comment]
> 我之前使用Nginx RTMP模块配置的流
> RTMP流：rtmp://192.168.1.1:1935/hls/dyxx
> HLS流：
> http://192.168.1.1:6080/hls/dyxx.m3u8
> HTTP-FLV流：
> http://192.168.1.1:6080/flv/dyxx
> 不知道lal是否也可以实现这样的流地址格式呢？

感谢提出建议，会尽快支持。
你的需求包含以下几点：

1. HLS流和HTTP-FLV流可共用一个端口
2. HLS流和HTTP-FLV流的url路径支持配置

另外，我有一个疑问，你举例中的HLS流的url路径中的`/hls/`，是希望

1. HLS流的url路径跟随RTMP推流中的`/hls/`（也即RTMP appname）变化
2. HLS流的url路径是一个静态可配置的url路径（也即不管RTMP appname是什么，HLS的url路径配置为`/hls/`就固定为`/hls/`）。

我个人倾向于第二种，感觉第一种没有太多实际使用场景。

**Comment by lystormenvoy** [comment]
> > 我之前使用Nginx RTMP模块配置的流
> > RTMP流：rtmp://192.168.1.1:1935/hls/dyxx
> > HLS流：
> > http://192.168.1.1:6080/hls/dyxx.m3u8
> > HTTP-FLV流：
> > http://192.168.1.1:6080/flv/dyxx
> > 不知道lal是否也可以实现这样的流地址格式呢？
> 
> 感谢提出建议，会尽快支持。
> 你的需求包含以下几点：
> 
> 1. HLS流和HTTP-FLV流可共用一个端口
> 2. HLS流和HTTP-FLV流的url路径支持配置
> 
> 另外，我有一个疑问，你举例中的HLS流的url路径中的`/hls/`，是希望
> 
> 1. HLS流的url路径跟随RTMP推流中的`/hls/`（也即RTMP appname）变化
> 2. HLS流的url路径是一个静态可配置的url路径（也即不管RTMP appname是什么，HLS的url路径配置为`/hls/`就固定为`/hls/`）。
> 
> 我个人倾向于第二种，感觉第一种没有太多实际使用场景。

我之前使用的是Nginx，所以http的服务是在http里面配置的，location配的什么就是什么，和rtmp的appname没什么关系。

**Comment by q191201771** [comment]
@lystormenvoy 
master分支的最新代码已经支持了，可以试试。

**Comment by lystormenvoy** [comment]
好的，谢谢

**Comment by q191201771** [comment]
这个issue的功能已经实现，
我将关闭这个issue，有需要的话可以随时重新打开，或者创建新的issue，感谢。
