### ISSUE TITLE
calcHeader可以修改地方

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#7]
func calcHeader(header *Header, prevHeader *Header, out []byte)函数可以修改的地方：
func calcHeader(header *Header, prevHeader *Header, out []byte) int {
	var index int = 0

	// 计算fmt和timestamp
	fmt := uint8(0)
	var timestamp uint32
	if prevHeader == nil {
		timestamp = header.TimestampAbs
	} else {

		//修改后.一个MSG内MsgStreamID一定是相同的,同时使用固定fmt3，原始的那几个判断条件执行后fmt始终为3
		fmt = 3
		if header.TimestampAbs > maxTimestampInMessageHeader {
			timestamp = header.TimestampAbs
		} else {
			timestamp = header.TimestampAbs - prevHeader.TimestampAbs
		}

		//修改前
		//if header.MsgStreamID == prevHeader.MsgStreamID {
		//	fmt++
		//	if header.MsgLen == prevHeader.MsgLen && header.MsgTypeID == prevHeader.MsgTypeID {
		//		fmt++
		//		if header.TimestampAbs == prevHeader.TimestampAbs {
		//			fmt++
		//		}
		//	}
		//	if header.TimestampAbs > maxTimestampInMessageHeader {
		//		timestamp = header.TimestampAbs
		//	} else {
		//		timestamp = header.TimestampAbs - prevHeader.TimestampAbs
		//	}
		//} else {
		//	timestamp = header.TimestampAbs
		//}
	}

**Comment by q191201771** [comment]
关于rtmp中message拆分打包成chunk部分：  

你提的这个修改，确实可以work，相当于去除了一些目前执行不到的代码分支逻辑，简化了流程。  

但是，这么做的前提，是不同message间不做参考。也即每个message的首个chunk都使用fmt 0，传输完整头信息。  
lal中，我是在调用calcHeader的上层做了这个保证。这点在原代码中有注释说明。  

而理论上，rtmp协议是允许不同message间也做参考的。这也是为什么它在fmt0和3之外设计了1和2格式。  
所以尽管我在调用calcHeader的上层保证了不同message不做参考，但是为了保证calcHeader自身的实现完整性，我决定现阶段还是保留calcHeader内部的判断。  

另外，chunk打包的地方修复了一个bug：  
将数据打包成rtmp chunk发送给vlc，时间戳超过3字节最大范围时，  
vlc认为fmt0和fmt3两种格式，都需要携带扩展时间戳字段，并且该时间戳字段必须使用绝对时间戳。  
（原有实现中，fmt3时，扩展时间戳字段使用的是相对时间戳，vlc不认）  
具体见这次提交：  
https://github.com/q191201771/lal/commit/5576b6659d44f67581f673b98cadae4b1cae21f1

**Comment by bigbao9494** [comment]
明白你的意思了。其实可以把一些设计上的思路或预留扩展写成注释，更多的注释还是好些，一是阅读代码的人更容易理解，二是不需要都来ISSUE了。
