### ISSUE TITLE
hevc 265 problem audio rtsp and block image and not support rtmp and flv server

### ISSUE THREAD

**Issue by goliveok** [q191201771/lal#75]
hi 

hevc 265 problem audio rtsp and block image and not support rtmp and flv server

error not support ac3 : ffmpeg -i input -c:v copy -c:a copy -f rtsp rtsp://host:port/id

-------------------------------------------------------------------------------------------------------------------------------------------
good run : ffmpeg -i input -c:v copy -c:a aac -f rtsp rtsp://host:port/id

ffmpeg :
image hevc frezzz and not audio
ac3 @ 0x55c229397c40] expacc 126 is out-of-range.26 bitrate=N/A speed=1.04x    
[ac3 @ 0x55c229397c40] error decoding the audio block

app lal :
2021/05/04 14:47:31.353880 ERROR invalid position. pos=0 - rtp_unpacker_avc_hevc.go:190
2021/05/04 14:47:31.353950 ERROR invalid position. pos=0 - rtp_unpacker_avc_hevc.go:190
2021/05/04 14:47:31.354015 ERROR invalid position. pos=0 - rtp_unpacker_avc_hevc.go:190
------------------------------------------------------------------------------------------------------------------------------------------

**Comment by q191201771** [comment]
What's the `input` exactly?
What's the origin audio codec of `input`?
Is it a file that you can submit to me for a test?
And could you submit the full log of lal?

**Comment by goliveok** [comment]
app = ffmpeg copy live mpegts to rtmp lal {  error not support hevc 265 } 
        and ffmpeg copy live mpegts to rtcp lal {  error not support ac3 audio and frezzzz }

for audio transcode to aac yes good play and frezz image 
good run : ffmpeg -i input -c:v copy -c:a aac -f rtsp rtsp://host:port/id

i need ffmpeg copy codec video and codec audio to rtmp or rtcp no transcode 

Thank you very much my friend

**Comment by q191201771** [comment]
Can you upload the output info of ffmpeg and the full log of lal?
Thanks.

**Comment by goliveok** [comment]
ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (*)

  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'http://*******************/live/liv.ts':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1918x1080 [SAR 960:959 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 25 tbc
    Stream #0:1[0x101](deu): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
[flv @ 0x55f664c31f00] Video codec hevc not compatible with flv
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
*****************************************************************************************
erro rtmp not support hevc

Video codec hevc not compatible with flv
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented

--------------------------------------------------------------------------------------

**Comment by goliveok** [comment]
2021/05/07 23:58:40.496867 DEBUG group size=0 - server_manager.go:157
2021/05/07 23:59:10.496859 DEBUG group size=0 - server_manager.go:157
2021/05/07 23:59:40.497499 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:00:10.496885 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:00:40.496825 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:01:10.497323 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:01:40.496803 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:02:10.497271 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:02:30.094220  INFO accept a rtmp connection. remoteAddr=127.0.0.1:38288 - server.go:66
2021/05/08 00:02:30.095682 DEBUG [NAZACONN1] lifecycle new connection. net.Conn=0xc000010018, naza.Connection=0xc00007e000 - connection.go:154
2021/05/08 00:02:30.096413  INFO [RTMPPUBSUB1] lifecycle new rtmp ServerSession. session=0xc00018c000, remote addr=127.0.0.1:38288 - server_session.go:95
2021/05/08 00:02:30.097368 DEBUG handshake complex mode. - handshake.go:249
2021/05/08 00:02:30.097491  INFO [RTMPPUBSUB1] < R Handshake C0+C1. - server_session.go:185
2021/05/08 00:02:30.097922  INFO [RTMPPUBSUB1] > W Handshake S0+S1+S2. - server_session.go:187
2021/05/08 00:02:30.098436  INFO [RTMPPUBSUB1] < R Handshake C2. - server_session.go:195
2021/05/08 00:02:30.099145  INFO [RTMPPUBSUB1] < R connect('liveok'). tcUrl=rtmp://127.0.0.1:1935/liveok server_session.go:342
2021/05/08 00:02:30.099429  INFO [RTMPPUBSUB1] > W Window Acknowledgement Size 5000000. - server_session.go:346
2021/05/08 00:02:30.099625  INFO [RTMPPUBSUB1] > W Set Peer Bandwidth. - server_session.go:351
2021/05/08 00:02:30.099747  INFO [RTMPPUBSUB1] > W SetChunkSize 4096. - server_session.go:356
2021/05/08 00:02:30.100132  INFO [RTMPPUBSUB1] > W _result('NetConnection.Connect.Success'). - server_session.go:361
2021/05/08 00:02:30.102024 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=releaseStream, header={CSID:3 MsgLen:32 MsgTypeID:20 MsgStreamID:0 TimestampAbs:0}, b=25, hex=00000000  02 00 0d 72 65 6c 65 61  73 65 53 74 72 65 61 6d  |...releaseStream|
00000010  00 40 00 00 00 00 00 00  00 05 02 00 03 33 33 33  |.@...........333|
 - server_session.go:316
2021/05/08 00:02:30.102215 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=FCPublish, header={CSID:3 MsgLen:28 MsgTypeID:20 MsgStreamID:0 TimestampAbs:0}, b=21, hex=00000000  02 00 09 46 43 50 75 62  6c 69 73 68 00 40 08 00  |...FCPublish.@..|
00000010  00 00 00 00 00 05 02 00  03 33 33 33              |.........333|
 - server_session.go:316
2021/05/08 00:02:30.102337  INFO [RTMPPUBSUB1] < R createStream(). - server_session.go:373
2021/05/08 00:02:30.102400  INFO [RTMPPUBSUB1] > W _result(). - server_session.go:374
2021/05/08 00:02:30.102732 DEBUG [RTMPPUBSUB1] pubType=live - server_session.go:401
2021/05/08 00:02:30.102800  INFO [RTMPPUBSUB1] < R publish('333') - server_session.go:402
2021/05/08 00:02:30.102892  INFO [RTMPPUBSUB1] > W onStatus('NetStream.Publish.Start'). - server_session.go:404
2021/05/08 00:02:30.103135  INFO [GROUP1] lifecycle new group. group=0xc0001ac000, appName=liveok, streamName=333 - group.go:133
2021/05/08 00:02:30.103264 DEBUG [GROUP1] [RTMPPUBSUB1] add PubSession into group. - group.go:288
2021/05/08 00:02:30.104700  INFO [HLSMUXER1] lifecycle new hls muxer. muxer=0xc0001b0000, streamName=333 - muxer.go:117
2021/05/08 00:02:30.104863  INFO [HLSMUXER1] start hls muxer. - muxer.go:122
2021/05/08 00:02:30.107634 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=FCUnpublish, header={CSID:3 MsgLen:30 MsgTypeID:20 MsgStreamID:0 TimestampAbs:0}, b=23, hex=00000000  02 00 0b 46 43 55 6e 70  75 62 6c 69 73 68 00 40  |...FCUnpublish.@|
00000010  18 00 00 00 00 00 00 05  02 00 03 33 33 33        |...........333|
 - server_session.go:316
2021/05/08 00:02:30.107773 DEBUG [RTMPPUBSUB1] read command message, ignore it. cmd=deleteStream, header={CSID:3 MsgLen:34 MsgTypeID:20 MsgStreamID:0 TimestampAbs:0}, b=24, hex=00000000  02 00 0c 64 65 6c 65 74  65 53 74 72 65 61 6d 00  |...deleteStream.|
00000010  40 1c 00 00 00 00 00 00  05 00 3f f0 00 00 00 00  |@.........?.....|
00000020  00 00                                             |..|
 - server_session.go:316
2021/05/08 00:02:30.107909 DEBUG [NAZACONN1] close once. err=EOF - connection.go:418
2021/05/08 00:02:30.108062  INFO [RTMPPUBSUB1] rtmp loop done. err=EOF - server.go:69
2021/05/08 00:02:30.108203 DEBUG [GROUP1] [RTMPPUBSUB1] del rtmp PubSession from group. - group.go:669
2021/05/08 00:02:30.108280  INFO [HLSMUXER1] lifecycle dispose hls muxer. - muxer.go:127
2021/05/08 00:02:30.496843  INFO erase empty group. [GROUP1] - server_manager.go:603
2021/05/08 00:02:30.497153  INFO [GROUP1] lifecycle dispose group. - group.go:245
2021/05/08 00:02:40.496849 DEBUG group size=0 - server_manager.go:157
2021/05/08 00:03:06.108552  INFO cleanup hls file path. streamName=333, path=/tmp/lal/hls/333 - group.go:1132

------------------------
lal

**Comment by q191201771** [comment]
HEVC over RTMP:
HEVC over RTMP is not supported by the RTMP specification. You may need to use an unofficial FFMPEG e.g. https://github.com/ksvc/FFmpeg

ac3 over RTMP:
I'm not familiar with ac3, I'm not sure if the RTMP specification support ac3, but lal does not support ac3 over RTMP apparently. I'll do more research. Have you used ac3 over RTMP before?

**Comment by goliveok** [comment]
Thank you very much for the excellent answers 
For my request 
i need  send live streaming h265 and copy codec audio and codec video to lal in any protocol

I do not need RTMP, I most need streaming h256 hevc to lal 
by: ffmpeg
http or rtp or rtcp or udp to lal

 not transcode

And I have a possible request :
on demoand stream ffmpeg to lal

**Comment by q191201771** [comment]
You wanna push streaming to lal and then do what?

**Comment by q191201771** [comment]
Can you send me a mpegts file represent your live mpegts？

1. save your http mpegts to file by http client tools e.g. wget, curl
2. send it to my email: 191201771@qq.com

**Comment by q191201771** [comment]
Close this issue since timeout.
Feel free to reopen it if needed.
