### ISSUE TITLE
lalserver中http类型的拉流服务（flv，ts，hls）支持配置url路径

### ISSUE THREAD

**Issue by q191201771** [q191201771/lal#77]
相关issue： #64

**Comment by goliveok** [comment]
hi my friend
Nice addition and excellent work :+1: ...

I have a note :

1: I tried this version and had some problems with sound  ffmpeg to rtsp hevc
copy video hevc from ffmpeg to rtsp  good
copy audio or add codec aac to rtsp good
commond example:
ffmpeg -re -i "http://*******hevc*****h265******" -c:v copy -c:a aac -f rtsp rtsp://127.0.0.1:5544/okok

$ffplay    rtsp://127.0.0.1:5544/okok    yes audio 
-------------------------------------------------------------------------------------------
$ffplay http://127.0.0.1:8081/hls/test110/playlist.m3u8     no audio
$ffplay http://127.0.0.1:8081/hls/test110/record.m3u8      no audio
$ffplay http://127.0.0.1:8082/live/test110.ts                      no audio and ( Takes long time to open the stream  )
------------------------------------------------------------------------
video yes
audio no
-----------------------------------------------------------------
log error ffplay
------------------
[hls @ 0x7f7454000bc0] decoding for stream 1 failedq=    0B f=0/0   
[hls @ 0x7f7454000bc0] Could not find codec parameters for stream 1 (Audio: aac (LC) ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls, from 'http://127.0.0.1:8080/hls/okok/playlist.m3u8':
  Duration: N/A, start: 350.700000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1918x1080 [SAR 960:959 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 25 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 0 channels, fltp
    Metadata:
      variant_bitrate : 0
[http @ 0x7f7454008f40] Opening 'http://127.0.0.1:8080/hls/okok/1620583400-36.ts' for reading

**Comment by q191201771** [comment]
lalserver中http类型的拉流服务（flv，ts，hls）已支持配置url路径。
