### ISSUE TITLE
HTTP_TS模块开发思路

### ISSUE THREAD

**Issue by bigbao9494** [q191201771/lal#9]
httpTS模块开发：
	1、和httpflv模块使用方法相同，客户端下载TS封装数据。
	2、设计基本可以参考httpflv模块，创建一个新的httpts的package
	   类似flv模块，在Group struct中添加一个成员变量httptsSubSessionSet map[*httpts.SubSession]struct{}来保存所有的httpts客户端信息。
	3、httpflv是直接在func (group *Group) broadcastRTMP函数中就完成数据转发，broadcastRTMP是Group的成员函数可以直接访问httpflvSubSessionSet。
	 httptsSubSessionSet需要在func (f *FragmentOP) writeFile函数中去遍历来完成转发，
	 这就需要在AddRTMPPullSession中创建NewMuxer时把httptsSubSessionSet的引用传递进去
	 最终还要在FragmentOP中引用，因为最终的TS数据转发会在func (f *FragmentOP) writeFile函数中实现

**Comment by q191201771** [comment]
嗯，首先，欢迎提交http ts的PR。风格一致性上尽量参考package httpflv的代码。

然后，在现有架构上回答你的问题。不同协议的连接对象的挂载关系管理，属于业务逻辑，应放在package logic中。协议package应该功能独立，只负责协议部分和连接部分。

接下来我会对这个项目做一次重构（额，重构时间点在我完成正在进行中的RTSP功能之后），重构的主要内容为在当前协议package之下再抽象一层，重构范围包含了package hls。所以你最好在我重构完成之后再开始http ts的工作。

如果你现阶段打算动手，注意两点：
1. 建立一个独立的package httpts，这个package不要依赖任何其他lal中已有package。即使现阶段package hls中已包含ts切片功能；即使现现阶段这样会带来双份的切片开销
2. 写代码前在这个issue回复我，我会为http ts单独建立一个分支，供你提交http ts功能的PR

**Comment by bigbao9494** [comment]
已经实现了效果刚刚的，现在依赖于HLS模块的TS复用，暂时就不提交。等待你重构后提交。
现在等你的RTSP模块啊………………
@q191201771

**Comment by q191201771** [comment]
master分支的lalserver已支持http-ts拉流。
@bigbao9494
