### ISSUE TITLE
arm32交叉编译失败

### ISSUE THREAD

**Issue by ChungTak** [q191201771/lal#92]
1.尝试交叉编译arm包出现以下错误，arm64没问题。
2.测试环境
  go version go1.16.5 linux/amd64
  ubuntu18.04
  lal 最新代码
3.测试过程
编译命令
`CGO_ENABLED=0 GOOS=linux GOARCH=arm go build app/lalserver/main.go`

错误日志
` github.com/q191201771/naza/pkg/nazaatomic
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:15:6: Int64 redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:19:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:19:6: Uint64 redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:24:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:25:20: (*Uint64).Load redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:31:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:29:20: (*Uint64).Store redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:38:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:33:20: (*Uint64).Add redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:44:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:38:20: (*Uint64).Sub redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:53:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:42:20: (*Uint64).Increment redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:61:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:46:20: (*Uint64).Decrement redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:69:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:50:20: (*Uint64).CompareAndSwap redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:77:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:54:20: (*Uint64).Swap redeclared in this block
        previous declaration at /root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_32bit.go:89:6
/root/go/pkg/mod/github.com/q191201771/naza@v0.19.1/pkg/nazaatomic/atomic_64bit.go:54:20: too many errors
`

**Comment by q191201771** [comment]
master分支修复了，方便可以再测试一下，感谢。

**Comment by ChungTak** [comment]
测试没问题`～～棒棒棒`！
