### ISSUE TITLE
/api/ctrl/start_pull 接口现在支持rtsp协议吗？

### ISSUE THREAD

**Issue by asdfsx** [q191201771/lal#93]
/api/ctrl/start_pull 接口现在支持rtsp协议吗？

**Comment by q191201771** [comment]
现在不支持，目前正在做的rtsp相关的支持包含：

- demo: pull rtmp 2 push rtsp
- lalserver: pub rtmp 2 sub rtsp
- lalserver: pull rtsp

支持后我会在这里回复，感谢。

**Comment by q191201771** [comment]
现阶段有个临时方案，可以使用/app/demo/pullrtsp2pushrtsp 或者 pullrtsp2pushrtmp 将rtsp拉回来转推至lalserver，

**Comment by asdfsx** [comment]
我现在就是用的这个方案。但是还是需要多写一个用来push的客户端。

**Comment by uliian** [comment]
我刚才看了一下group__relay_pull的实现，感觉的rtmp耦合很紧，如果要支持其他pull，得改动的地方挺多，感觉需要进行一些抽象，这个工作短期看来不太好实现吧，感觉owner亲自操刀比较稳妥

**Comment by q191201771** [comment]
> 我刚才看了一下group__relay_pull的实现，感觉的rtmp耦合很紧，如果要支持其他pull，得改动的地方挺多，感觉需要进行一些抽象，这个工作短期看来不太好实现吧，感觉owner亲自操刀比较稳妥

感谢回复，我正在做这方面的支持。
如果对代码感兴趣，建议可以看看group中的其他代码，比如rtsp转rtmp的remuxer。

**Comment by q191201771** [comment]
这个功能已经完成，issue先关闭了，有需要请重新打开或创建新的issue，感谢。
