### ISSUE TITLE
准备支持rtp的ps私有流么?

### ISSUE THREAD

**Issue by zwczou** [q191201771/lal#94]
首先感谢你的开源项目，我稍微了解了下，发现项目用起来很简单方便，是我想要的库。

就是payload type ＝96时候，是ps流，然后ps流里面包含了视频流跟音频流。

目前国标gb28181的视频监控里面很多都是这个ps流，而且ps流一般都是h264跟g711a的音频。

如果您准备支持，没有环境的话，我可以为你提供一些视频rtp ps流。也可以提供一些我写的简单相关解码。

**Comment by q191201771** [comment]
提供视频rtp ps流是指网络抓包文件吗，可以给我看看，

**Comment by ChungTak** [comment]
这里有摄像机的ps流抓包文件
https://github.com/ty6815/AvStackDocs/blob/master/test%20file/format/02c27467_1593177349.ps    海康
https://github.com/ty6815/AvStackDocs/blob/master/test%20file/raw/01e168e1_1995306245.ps

**Comment by q191201771** [comment]
gb28181和ps已经初步支持了，看这个文档： https://www.yuque.com/pengrl/public/ewgga7
