### ISSUE TITLE
lalserver relay pull动态回源功能支持rtsp拉流回源

### ISSUE THREAD

**Issue by q191201771** [q191201771/lal#98]

**Comment by opo2000tw** [comment]
請問一下如何使用拉流回源? 

是否可以取代 pullrtsp2pushrtsp 推流呢 

謝謝

**Comment by q191201771** [comment]
lalserver的这个特性目前还没有支持，有空我会加上，感谢。

**Comment by q191201771** [comment]
HTTP-API控制的relay pull回源拉流功能已支持rtsp协议，可以试试，文档见：
https://pengrl.com/lal/#/HTTPAPI?id=_21-apictrlstart_relay_pull

**Comment by q191201771** [comment]
这个功能已经完成，issue先关闭了，有需要请重新打开或创建新的issue，感谢。
